### ISSUE TITLE
Directed slow crawling / predict full text value from title+abstract

### ISSUE THREAD

**Issue by gbgbg** [ajratner/dd-genomics#104]
We can always get access to say 20 papers per journal a day. If we wanted to utilize that to our advantage how could we? One way would be:
Once we have our pipeline together, analyze full text papers to explicitly ask:
1 what added info do we get from full text thatwe do not get from title+abstract
2 can we predict which full texts will be most valuable from title+abstract alone
3 use the prediction scheme we've built to slow-crawl for valuable papers

I can further develop this in due course, as it is still a ways out.
I would definitely not want to get in the way of seeing us squeeze what we have first.

**Comment by Colossus** [comment]
byoo1 is on this
