### ISSUE TITLE
UPGRADE TO dd 0.7.0

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#116]
Reiterating because we are diverging too far from master... I am putting some bugfixes into our codebase on raiders2, that are in 0.7.0 but not in ours... we will increasingly miss out on these sorts of changes if we don't switch

So, as soon as the big run of deepdive is done (almost!), we should switch right away I think... @Colossus I will let you know when we're here!

Note that this doesn't necessarily include DDLog, although this could be nice too

@Colossus I'm assigning to you because not too much to do other than read up on the changes -> 0.7.0.  I've already done the upgrade once for my tables stuff, so am up to speed.  However if this is anything but trivial I can help, lmk

**Comment by Colossus** [comment]
See the comment in #14 . Close this at any point. We're basically there.

**Comment by Colossus** [comment]
I've been running on 0.7.0 for the last two weeks.
