### ISSUE TITLE
Next parser run: Extract ISSN for journals as well

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#139]
This will get us rid of 90% of the journal name issues

**Comment by Colossus** [comment]
This is done from the parser side. Now rerun, load into DB and actually USE the ISSNs!

**Comment by gbgbg** [comment]
Bye bye 1.5 million journals?

-Gill

**Comment by Colossus** [comment]
For sure

**Comment by gbgbg** [comment]
Don't answer in English. 
I can wait as long as it takes to see an answer in numbers like  "1,533,444 --> 34,567 journals"
Big data maan, big data...
-Gill

**Comment by Colossus** [comment]
can't run now, preparing holdout set with huge run
