### ISSUE TITLE
Transition to new deepdive release

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#14]

**Comment by netj** [comment]
This should be straightforward if you look at the [DeepDive app structure doc](http://deepdive.stanford.edu/doc/advanced/deepdiveapp.html) and the rewritten [examples in the DeepDive source tree](https://github.com/HazyResearch/deepdive/tree/master/examples/spouse_example/postgres/tsv_extractor), but do let me know if you need any help or advice!

**Comment by ajratner** [comment]
Thanks!

**Comment by ajratner** [comment]
Marking as low priority for now... @Colossus next time we do a big code cleanup / re-org we can do this too

**Comment by Colossus** [comment]
This is straightforward. You need to do only a few things:
- Prepend `deepdive/util` to your path, if you haven't done so already
- in `env_local.sh`, add the following: 
  export DBPASSWORD=
  export DEEPDIVE_JDBC_DRIVER=org.postgresql.Driver
  export DEEPDIVE_JDBC_URL="jdbc:postgresql://"${PGHOST}":"${PGPORT}"/"${DBNAME}
- In deepdive/util, execute one of the following commands:
  
  ```
  ln -s format_converter_mac format_converter && ln -s sampler-dw-mac sampler-dw
  ```

or the same for `-linux`.

If you get a strange error like `n_vars == n_factors` or something like that during inference, you forgot to do the last step. Please repeat it until success.

I'm running DD0.7 exclusively now. @ajratner feel free to close this when you're done with the transition too.

**Comment by netj** [comment]
@Colossus your changes shouldn't be necessary if you just replace the `sbt` command with `deepdive env java ...`.  See http://deepdive.stanford.edu/doc/changelog/0.7.0-alpha.html

**Comment by Colossus** [comment]
@netj OK sounds cool thanks!
