### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by senwu** [ajratner/dd-genomics#140]
When I try to run it on madmax4 with Python 2.6.2.

I got this syntax error:
senwu@madmax4:~/deepdive/app/dd-genomics$ python code/gene_extract_candidates.py 
Traceback (most recent call last):
  File "code/gene_extract_candidates.py", line 10, in <module>
    import config
  File "/lfs/madmax4/0/senwu/deepdive/app/dd-genomics/code/config.py", line 31
    'short_words' : {'the', 'and', 'or', 'at', 'in', 'see', 'as', 'an', 'data', 'for', 'not', 'our', 'ie', 'to', 'eg', 'one', 'age', 'on', 'center', 'right', 'left', 'from', 'based', 'total', 'via', 'but', 'resp', 'no' } 
                          ^
SyntaxError: invalid syntax

Do you have idea?

**Comment by Colossus** [comment]
hmmm ... we're using python 2.7.3 on raiders2. I've never seen this error before ... If you want to run on raiders2, tell me, I'm just parsing something but can stop anytime

**Comment by senwu** [comment]
Thanks for your information... No, I don't want to bother your runs.. Are there any other machines that I can run genomics application?

**Comment by Colossus** [comment]
No, never tried so far on other machines. I didn't even know GreenPlum was installed on madmax ... I suspended parsing for the moment. I would probably not even have started it if I had known it would take so long. I'll maybe restart it tomorrow night if I see nothing's going on; it's 90% done but will probably take 1-2 hours.

**Comment by Colossus** [comment]
BTW w/r/t raiders2: My path looks like this: `/lfs/raiders2/0/jbirgmei/deepdive/util:/afs/cs.stanford.edu/u/jbirgmei/local/bin:/dfs/scratch1/netj/wrapped/greenplum:/usr/kerberos/sbin:/usr/kerberos/bin:/afs/cs/software/sbin:/afs/cs/software/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games`

If you're getting weird database errors, definitely try prepending netj's `wrapped/greenplum` directory

**Comment by Colossus** [comment]
(But this just as a sidenote, not w/r/t the original error)

**Comment by senwu** [comment]
Can you add a note about running the python script with python version >2.7.x? Thanks...

**Comment by Colossus** [comment]
OK

**Comment by chrismre** [comment]
We should check the version number in the script. Perhaps?
