### ISSUE TITLE
"Error with row" during pheno features extraction due to dependency path errors

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#145]
See e.g. this: 
- Error with row: <Row(
- dep_paths=['amod', '', '', 'nn', 'prep_of', 'vmod', '', 'det', 'nn', 'nn', 'nn', 'nn', 'agent'], 
- lemmas=['molecular', 'determinant', 'of', 'trif', 'proteolysis', 'mediate', 'by', 'the', 'hepatitis', 'c', 'virus', 'ns3/4a', 'protease'], 
- ners=['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'], 
  * section_id=Ref.115, 
- sent_id=1, 
- mention_id=23202496_Ref.115_1_8_8_EXACT_HP:0012115, 
- words=['Molecular', 'determinants', 'of', 'TRIF', 'proteolysis', 'mediated', 'by', 'the', 'hepatitis', 'C', 'virus', 'NS3/4A', 'protease'], 
- mention_wordidxs=[8], 
- dep_parents=[2, 0, 0, 5, 2, 2, 0, 13, 13, 13, 13, 13, 6], 
- poses=['JJ', 'NNS', 'IN', 'NN', 'NN', 'VBN', 'IN', 'DT', 'NN', 'NN', 'NN', 'NN', 'NN'], 
- doc_id=23202496
- )>

Here, multiple words want word 13 as their dep_parent, but the number of words is only 13 (which with 0-indexing leads to all these errors). How can we fix the dependency paths?

**Comment by Colossus** [comment]
@ajratner OMFG. I think we have a huge problem with the dependency paths. ddlib expects the dep_parents to be -1-based (such that the root has index -1), but we provide 0-based dependency paths. So while the dependency paths we get are good, ddlib parses them off-by-one. See line 94 in deepdive/ddlib/ddlib/dd.py . Do you think this is the right diagnosis?

@gbgbg I KNOW I'LL EAT MY HAT

**Comment by ajratner** [comment]
@Colossus yes the dep_parents are 1-indexed, with 0 being the root / null path.  So there's nothing wrong with this dep path... where does the error come from?  I'm assuming some code that we introduced which mistakenly expects 0-indexing...?

I'll take a look at ddlib but I'm fairly sure it supports this indexing scheme... although I will go double-check right now!

**Comment by Colossus** [comment]
@ajratner The point is that DDLib expects dependency paths to be 0-indexed, with the root getting -1. What we're having is that the root is 0 and the path is 1-indexed. I just fixed this for pheno_features only, test reran, and all these "ERROR WITH ROW" things are fixed. Which also means that feature extraction so far has been one-off, and I think we have no clear indication how many sentences we used to lose because of this one

**Comment by Colossus** [comment]
It might be every sentence was omitted where the dependency path parents contained a link to the last word in the sentence.

**Comment by ajratner** [comment]
@Colossus It seems clear then that somehow this was the cause of the `IndexError` that was being caught & printed out as the mentioned error

_However_ I do not think this is an error with `ddlib`.  First of all, if you look at the `ddlib` code- such as the line you highlighted- for computing minimum paths in the dependency graph, this is not actually dependent on determining the root node correctly.  As I read it, the algorithm gets the path from words A and B to the root node _or till a cycle is reached_, and then takes the earliest intersection of the two paths.

Especially with the wrong root node (`-1` vs. `0`) this algorithm may not be the nicest or most efficient... but it shouldn't really be affected in terms of accuracy by the root node choice

Still looking for what might be causing the error- either way seems like you're right it has to do with this -1 vs 0 indexing of the root, good catch!

**Comment by gbgbg** [comment]
@colossus no need to eat your hat. Just work carefully and methodically. When you remove all the ticks, I do believe there will be a big bad dog underneath. The dog bites the competition and we win :)
-Gill
