### ISSUE TITLE
Hook G & P up to config.py

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#15]

**Comment by ajratner** [comment]
@Colossus I'll handle this for P!

**Comment by Colossus** [comment]
@ajratner Please ./run.sh pheno_candidates , I get: ``NameError: global name 'onto_path' is not defined'' (not removing this myself; I think there's also a trailing backslash in line 155). Also, shouldn't it be "if keep_word" instead of "if not keep_word"?

**Comment by Colossus** [comment]
@ajratner ah bs forget about the trailing backslash that's obviously OK ... but the other error is still there

**Comment by ajratner** [comment]
@Colossus Ok my bad I left out a line when putting a function into a util file.  Pushed fix.

If you're referring to "if not keep_word" in pheno_extract_candidates:83, that's correct, this bit of code is looking for a certain number of consecutive stop words- if found it will 'split' on this segment, i.e. not consider candidate n-grams containing it

**Comment by Colossus** [comment]
@ajratner sounds good thanks
