### ISSUE TITLE
Many genes are counted multiple times because they have different Ensembl IDs

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#153]
E.g., in our genepheno association list, we have:

HP:0001370  Rheumatoid arthritis    ENSG00000204490:TNF 770
HP:0001370  Rheumatoid arthritis    ENSG00000206439:TNF 770
HP:0001370  Rheumatoid arthritis    ENSG00000223952:TNF 770
HP:0001370  Rheumatoid arthritis    ENSG00000228321:TNF 770
HP:0001370  Rheumatoid arthritis    ENSG00000228849:TNF 770
HP:0001370  Rheumatoid arthritis    ENSG00000228978:TNF 770
HP:0001370  Rheumatoid arthritis    ENSG00000230108:TNF 770
HP:0001370  Rheumatoid arthritis    ENSG00000232810:TNF 770

(This is kinda the worst case though.)

We should get rid of those. It will presumably cut down our GP count a bit, but these different ENSG identifiers are just not useful. Perhaps pick one representative ENSG identifier and link it to all other ENSG IDs for the same gene, if that's possible.

**Comment by chrismre** [comment]
Agreed: The entity link here (deciding to link to a single one) is easy. I'd assume there is some meaning to that field, and I'd hate to lose information...  however, you can produce a view that collapses them

**Comment by gbgbg** [comment]
@colossus: it is important for you to understand why this is happening - the crux lies in the genomics. There is one clue on my notes from tonight. Another clue from a TNF query of the ucsc browser is pasted below. A third comes from the list of hg19 chromosomes:
http://genome.ucsc.edu/cgi-bin/hgTracks?hgsid=13095744&chromInfoPage=

Understanding this will give you the right way to collate duplicate gene entities (at the gene level). 
Let me know if you cannot figure this out. 

TNF (uc011jjy.2) at chr6_ssto_hap7:2875093-2876913 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc011jjx.3) at chr6_ssto_hap7:2874145-2876913 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc011iol.2) at chr6_qbl_hap6:2837932-2839752 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc011iok.3) at chr6_qbl_hap6:2836982-2839752 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc011hrb.2) at chr6_mcf_hap5:2923998-2925818 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc011hra.3) at chr6_mcf_hap5:2923050-2925818 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc011gyl.2) at chr6_mann_hap4:2887176-2888996 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc011gyk.3) at chr6_mann_hap4:2886228-2888996 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc011gcc.2) at chr6_dbb_hap3:2829833-2831653 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc011gcb.3) at chr6_dbb_hap3:2828885-2831653 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc011fef.2) at chr6_cox_hap2:3053908-3055728 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc011fee.3) at chr6_cox_hap2:3052960-3055728 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc011emr.2) at chr6_apd_hap1:2859027-2860830 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc003nuj.3) at chr6:31544292-31546112 - Homo sapiens tumor necrosis factor (TNF), mRNA. TNF (uc003nui.4) at chr6:31543344-31546112 - Homo sapiens tumor necrosis factor (TNF), mRNA.

-Gill

**Comment by amwenger** [comment]
(looks like @gbgbg and I are processing this in parallel)

For the non-genomicists:
- A [gene isoform](https://en.wikipedia.org/wiki/Gene_isoform), or transcript,  is a combination of exons (5' UTR, 3' UTR, and coding sequence) that are transcribed from a specific locus in the genome to a messenger RNA.  The ENSEMBL gene set assigns ENST identifiers to isoforms/transcripts.
- Isoforms that have overlap in the constituent exons are organized into a [gene](https://en.wikipedia.org/wiki/Gene), a locus in the genome that encodes an RNA product.  The ENSEMBL gene set assigns ENSG identifiers to genes.  Each ENST is assigned to one and only one ENSG.  The mapping of ENST->ENSG is many-to-one.
- Although different isoforms of a gene produce slightly different proteins, all isoforms are typically treated as having the same function.  Publications almost always discuss genes, not isoforms.
- Some regions of the genome display enough variation in the human population that it is not possible to derive a single reference representation.  For such regions, the genome assembly includes "haplotype" chromosomes, one for each of the versions seen in the human population.  Haplotype chromosomes have names like "chr6_apd_hap1" and "chr17_ctg5_hap1".  The GRCh37/hg19 assembly has nine "haplotype" chromosomes: 7 for chr6, 1 for chr17, and 1 for chr4.
- The genes that are present in the regions with multiple representations have versions with completely different, non-overlapping chromosome coordinates.  Thus, they are assigned separate ENSG identifiers.

The TNF gene is present in the region of chr6 that has multiple representations in the hg19 assembly.  You see 8 different ENSG identifiers for TNF, 1 for the version of chr6 proper and 7 for the versions on each of the 7 chr6 haplotype chromosomes.

When you pick a canonical identifier, please pick the version from the proper chromosome, not the haplotype chromosomes.

**Comment by gbgbg** [comment]
It is slightly worse than parallel - @collosus, this is in my notes from 2am. Please go over those first if you can. If you find them too cryptic I can dump them all as issues on DDG. I thought some belonged in dashboard git but couldn't find such an entity on neither hazyresearch nor @netj 's repos. I may have missed it.

**Comment by Colossus** [comment]
Gill, you should start writing my name like "@Colossus", otherwise this other guy is gonna constantly get messages from our threads
