### ISSUE TITLE
Change Dashboard so it shows high and low end of distribution

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#154]
In almost every table, I select entries by something like (SELECT ... FROM ... **ORDER BY count DESC LIMIT 1000**). (This is the case, e.g., in the gp association links, journal statistics etc.) In the ideal case, we should show high, median and low end of every distribution in the Dashboard tables.

**Comment by gbgbg** [comment]
Great idea, unless the list is short enough you can show the full distribution...
