### ISSUE TITLE
Integrate Sen's pull request / switch to ddlog + view!

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#155]
Hey @Colossus we can go through this together sometime next week or you can look over, either way @SenWu and I just checked in, he is going to submit his stuff (the ddlog app file, some view stuff, etc.) as a pull request with notes on some stuff to look out for when integrating with our current code

**Comment by Colossus** [comment]
OK sounds great

**Comment by Colossus** [comment]
I'll have a look at it, but yeah let's meet next week and figure it out from there. Currently trying a few things on genomics-production-2, but raiders is a bit sluggish at the moment

**Comment by chrismre** [comment]
As a carrot, if you do this... you get VIEW for free... just sayin' @gbgbg

**Comment by gbgbg** [comment]
@Colossus (or whatever your confusing alias may be), @ajratner, I think @chrismre is hinting that sometime next week is an ill defined target ;) think of me all alone in my hotel room... no porn on p-card... If only I had a room with a...

**Comment by Colossus** [comment]
@gbgbg "confusing alias" ... look who's talking ;)

**Comment by chrismre** [comment]
Do we have a view instance I can see? :)

**Comment by Colossus** [comment]
@SenWu How do I actually run from `app.ddlog`? If I hit `./run.sh` I think it just uses `application.conf`, I think. I looked through your documentation at `http://deepdive.stanford.edu/doc/basics/ddlog.html`, but didn't find anything on how to start it

**Comment by senwu** [comment]
@Colossus The DD0.7 will take app.ddlog as input to run the whole pipeline. It will compile app.ddlog to deepdive.conf and run deepdive.conf.(There is no application.conf anymore).

**Comment by netj** [comment]
FYI the full deepdive.conf compiled from ddlog will be kept for the record at `run/LATEST/deepdive.conf` or `run/ABORTED/deepdive.conf` if some error happened.  Currently executing runs will be pointed by `run/RUNNING/deepdive.conf`.  You can still keep deepdive.conf at the top to put whatever config you need to override.  They get merged at the time of `deepdive run`.

**Comment by Colossus** [comment]
@SenWu @netj OK, will try. Thanks!

**Comment by Colossus** [comment]
@SenWu Sen, it would be really great if you just dropped the tables that the deepdive application actually needs. Currently, the whole database is swiped clean when executing `deepdive initdb`.

**Comment by senwu** [comment]
From the pipeline Alex sent to me, the full pipeline only need the sentences table(user need load sentence to that table), right? All other tables, e.g., gene_mentions, pheno_mentions, will be created by deepidve? Do we need any other data?

**Comment by Colossus** [comment]
The issue was as follows. I wanted to load sentences_input. It turns out that the format of sentences_input in ddlog is not the same as in the original (at least `ref_doc_id` is missing). I usually copy tables between databases using `pg_dump`. So I had to drop `sentences_input` in the target database, copied `sentences_input`, renamed it to `sentences_input_orig` and then reran `deepdive initdb` again. Upon which I discovered that `sentences_input_orig` was gone.

**Comment by Colossus** [comment]
Apart from that, we do in fact have a second input table: `doc_metadata`, which would be great if it wasn't dropped if something in the schema changes. In general, it happens pretty often that in some table a field is added or split or whatever. Creating some of these table contents takes huge amounts of time, for example the gene candidates. It would be great if `deepdive initdb` could be configured to recreate only certain tables, or at least not swipe the whole database. In the latter case, we could just save existing tables and rename them again after `deepdive initdb`.

**Comment by ajratner** [comment]
Hey @Colossus sorry I put this up as an issue / feature request, see HazyResearch/deepdive#351

Hopefully will be in deepdive soon but for now we should probably load data on our own incrementally

**Comment by chrismre** [comment]
Sigh. This issue is crazy making... it should have been done a long time
ago... Can you link to it AR?

**Comment by ajratner** [comment]
Linked above

**Comment by Colossus** [comment]
done
