### ISSUE TITLE
Cannot start genomics NPM API

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#156]
Hey @ajratner , could we go through this at some point, or do you know what's up? Did you maybe not push some sources? I was just trying to start the genomics API, but couldn't and got the following error:

```
Error: Cannot find module '/lfs/raiders2/0/jbirgmei/dd-genomics-production/api/genomics/bin/www'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:935:3
```

**Comment by ajratner** [comment]
Hey @Colossus sorry for the delayed response.  The file referenced in the error above had been accidentally excluded by a `.gitignore` rule- try now and lmk what happens?

**Comment by Colossus** [comment]
Works better, thanks --- the initial page now loads, but then pretty quickly the backend crashes with the message:

```
/Users/jbirgmei/Stanford/Bejerano/dd-genomics/api/genomics/server/routes/index.js:10
var query = client.query("SELECT COUNT(*) FROM genepheno_entity_level;");
                  ^
TypeError: Cannot read property 'query' of null
```

**Comment by Colossus** [comment]
OK nevermind, sorry. This error occurs only on my own machine, works on raiders2. Going to close.
