### ISSUE TITLE
Do Gene, Pheno, Variant, Acronyms candidate extraction during the same pipe

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#157]
It's a waste of time to pipe the same information four times through four different noodle machines. We can do all of this stuff in one run and maybe save a lot of time on candidate extraction.

**Comment by Colossus** [comment]
DeepDive might not support multi-table output natively, but we can always pipe to a single messy table and SQL separate afterwards

**Comment by Colossus** [comment]
Elaborate further: I think a lot of the time is currently spent on boilerplate work on each extractor. The SELECT query itself takes a  lot of time, I think. Splitting all these array fields and building the dependency DAG also takes some time.

**Comment by chrismre** [comment]
Please don't hack around this :) @netj or @feiranwang or @SenWu can put in a shared scans optimization that would do this. That's in the plans after we do the next pass (and distant supervision). 

Chris
