### ISSUE TITLE
list index out of range in gene _extract_features.py

### ISSUE THREAD

**Issue by senwu** [ajratner/dd-genomics#161]
I tried to run 1% of pmc data, and got the following error in gene
_extract_features.py which maybe a potential issue of udf:

14:00:12.831 [Thread-47][Helpers$(akka://deepdive)][Helpers$] INFO  Traceback (most recent call last):
14:00:12.831 [Thread-47][Helpers$(akka://deepdive)][Helpers$] INFO    File "app_main.py", line 72, in run_toplevel
14:00:12.832 [Thread-47][Helpers$(akka://deepdive)][Helpers$] INFO    File "/lfs/madmax4/0/senwu/deepdive/app/dd-genomics/code/gene
_extract_features.py", line 58, in <module>
14:00:12.832 [Thread-47][Helpers$(akka://deepdive)][Helpers$] INFO      util.run_main_tsv(row_parser=parser.parse_tsv_row, row_fn=g
et_features_for_row)
14:00:12.832 [Thread-47][Helpers$(akka://deepdive)][Helpers$] INFO    File "/lfs/madmax4/0/senwu/deepdive/app/dd-genomics/code/extr
actor_util.py", line 183, in run_main_tsv
14:00:12.833 [Thread-47][Helpers$(akka://deepdive)][Helpers$] INFO      lines_out += row_fn(row)
14:00:12.833 [Thread-47][Helpers$(akka://deepdive)][Helpers$] INFO    File "/lfs/madmax4/0/senwu/deepdive/app/dd-genomics/code/gene
_extract_features.py", line 38, in get_features_for_row
14:00:12.834 [Thread-47][Helpers$(akka://deepdive)][Helpers$] INFO      generic_features = [f._replace(name=feat) for feat in ddlib
.get_generic_features_mention(sentence, span)]
14:00:12.834 [Thread-47][Helpers$(akka://deepdive)][Helpers$] INFO    File "/lfs/madmax4/0/senwu/local/lib/python/ddlib/gen_feats.p
y", line 82, in get_generic_features_mention
14:00:12.834 [Thread-47][Helpers$(akka://deepdive)][Helpers$] INFO      if sentence[span.begin_word_id].word[0].isupper():
14:00:12.835 [Thread-47][Helpers$(akka://deepdive)][Helpers$] INFO  IndexError: list index out of range
14:00:15.345 [default-dispatcher-4][extractorRunner-extraction_rule_16][ExtractorRunner] ERROR java.lang.RuntimeException: Failure 
when executing script: /lfs/madmax4/0/senwu/deepdive/app/dd-genomics/run/20150828/135345.500996966/tmp/exec_parallel_udf.sh

**Comment by ajratner** [comment]
This could be due to duplicates, although I never had this issue.  Did you
follow the instructions on the README to delete duplicates?

**Comment by Colossus** [comment]
I just ran the gene extractor this morning on the full dataset and didn't have any issues.

Agree with @ajratner this sounds like what we had with duplicates. To get rid of duplicates in `sentences_input`, please execute `DELETE FROM sentences_input where (doc_id, section_id, sent_id) IN (SELECT doc_id, section_id, sent_id FROM sentences_input GROUP BY doc_id, section_id, sent_id HAVING count(*) >= 2);`

**Comment by senwu** [comment]
My mistake, after deleting duplicates, it passed.
