### ISSUE TITLE
clustype > Stanford NER?

### ISSUE THREAD

**Issue by gbgbg** [ajratner/dd-genomics#164]
"ClusType: Effective Entity Recognition and Typing by Relation Phrase-Based Clustering" just presented at the meeting im in. Notice Table 6 performs NER much better than Stanford's ??
http://shanzhenren.github.io/ClusType/

**Comment by chrismre** [comment]
I'd be stunned if we weren't better than that baseline. This is something we are very good at. We could use it as input--but I don't see a major win here. Let's try it out!
- Update I have been corrected and we're trying it out :)

**Comment by gbgbg** [comment]
Chris,
For ref I wasn't thinking this beats us. They claim to beat one of the modules on which you build. Anyway - your system, obviously your call. I just wanted to bring this to your attention / evaluation. 
Best,
-Gill

**Comment by chrismre** [comment]
If they're helpful we should use them. It's not a beat not us thing, I
realized it sounded like that (which was _not_ my intention, and why I
corrected the comment).

My impression was that (a) NER is not our bottleneck right now,  (b) I've
had difficulty replicating the quality in those clustering approaches in
the past, and (c) they don't scale as well. My reaction was wariness to
using time to introduce these tools for those reasons. That said, could be
a valuable signal... and I think we do have some places where bad NER is
hurting us in the short term (or so I learned)... however, we seem to
already use many of the same signals... it's just not clear to me it is
actually what hurts us now and could be a distraction.

Chris

**Comment by Colossus** [comment]
not on the horizon
