### ISSUE TITLE
Enhance Dashboard with Gill's wishes

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#165]
Gill 8/27

```
146,577 unique association genephenos (E > 0.9)
47,167 unique causation genephenos (E > 0.9)
```
- "23,589 unique gene candidates (true/null)"
  what's the size of our dictionary of all unique genes?
- "7,454 unique pheno candidates (true/null)"
  as above - how many phenotype terms do we have?
- in gill/most-frequent/genes-candidates
  - p.1 TNF appears as multiple different genes because its in the MHC locus (multiple versions of chromosome). Fix anything?
  - Same with DDR1 closing the top 1,000
  - there seems to be a healthy correlation between the top genes here and pubmed's "see NNN articles about GGGG gene function"
  - For false negatives - be interesting to pull genes with high article count in pubmed and low in our extractions!
  - When sorting on entity it would be helpful to sort on gene name suffix instead (or in addtion) to current sort that sorts on ENSG accessions. 
  - If sorting on gene names, could also have a view where all genes with 0 counts are interspersed (w different line colors) with the ones that have positive counts. That of course will be a list of all and not just the top 1,000. Again - feels helpful in hunting for false negatives.
  - Another reason for this (if browser can support it) is a lot of the G-P associations that would make a killing for us will NOT appear a large number of times. Most of the stuff that appears most frequently will be unrelated to the type diseases we are trying to solve.
- There are 6 different gill/most-frequent/genes-*
  If possible I would combine them into a single table w 7 columns (and all 20+,000 genes)
- Similarly it would be great to combine gill/most-frequent/phenos-\* 
  - and also show entries with 0s (ie all entries).
- Terms like HP:0010864 "Intellectual disability, severe" and HP:0001256 "Intellectual disability, mild" are both shown in the interface as "Intellectual disability" (truncated at comma)
  - The default sort of gill/most-frequent/phenos-in-cause-pair-cand is not obvious. See p. 40 where the last two terms have more counts than those above them. 
  - Similar anomalies in the default views of the last page of other phenos- pages. (but not genes-).
- pairs- 
  - Interesting for acronym resolution: I have a feeling the frequent pair HP:0012531 Pain - ENSG00000129988:LBP, is really about LBP = lower back pain. But I may be wrong!
  - It would be great to sort ENSG00000129988:LBP column on gene name and not ENSG accession (as above).
- per-journal
  - Sort gill/per-journal/gene-per-journal on gene_infs_per_doc, and I _love_ what I see there. The right journals shoot to the top. 
  - What are the journals near the top that I've never heard of like "International Journal of Molecular Sciences" "BioMed Research International"
  - It would be nice to resolve journal name on ISSN. E.g., in the top performers we have neck to neck "British Journal of Cancer" and "Br. J. Cancer" which map to same ISSN in the NLM catalog. With very similar numbers its not even clear if they are disjoint or overlapping.

**Comment by chrismre** [comment]
Is this good or bad? :)

**Comment by Colossus** [comment]
This is generally good. Just a few additional queries
