### ISSUE TITLE
Add first part of section_id (Title, Abstract, Body) as a feature

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#166]
The language difference issues between Titles, Abstracts and Bodies (if any) should then dissolve by magic

**Comment by ajratner** [comment]
Haha- like the prognosis. But this is a great idea to try / evaluate

**Comment by gbgbg** [comment]
Nice idea :) If magic does occur I would consider further breaking down body into intro results methods and discussion, where easy. 
Each of these parts is definitely written differently.

**Comment by ajratner** [comment]
@Colossus @gbgbg I have some doubts that breaking down into specific sections will be "easy" in the sense of solved in an hour with one or two heuristic rules- at scale at least.  

Perhaps I'm wrong.  But I'm guessing there are many slightly different ways to label the sections, and many slightly different ontologies of what types of sections are present

Two main ways come to mind:
1. Modify the XML parser to grab section titles, and then just include these as features for the existing inference variables (seems pretty quick, worth trying?)
2. Create a new multinomial  inference variable for "section type" (not too hard conceptually but would take a bit more doing)

@chrismre @zhangce Have we done classification of document sections in any other application before, e.g. paleo?

**Comment by Colossus** [comment]
this would be useless as far as I see now
