### ISSUE TITLE
Split gene table gene ID into ensembl ID, name and canonical name

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#168]
Currently the entity is something like `ENSGXXXXXXXX:GENE_NAME`. There are a number of problems with this approach: First, some canonical genes exist in multiple copies and isoforms, and the ENSG part is not unique, making us double count (#153). Second, the GENE_NAME part does not always refer to the canonical name of the gene, again making us over-count. We got to change the schema once again.

**Comment by amwenger** [comment]
I proposed the `ENSGXXXXXXXX:GENE_NAME` scheme to help me in MindTagger.  The original idea was to use `ENSGXXXXXXXX:CANONICAL_GENE_NAME` in place of `ENSGXXXXXXXX`.  I know many gene names but no ENSG numbers; so, the gene name helped me to tag a candidate gene mention for whether it was linked to the proper gene entity.  Before that, I had to look up each ENSG number.

The specific `ENSGXXXXXXXX:GENE_NAME` scheme is not important.  What is important is to provide an understandable name for gene and phenotype entities in MindTagger and other tools intended for humans.

**Comment by Colossus** [comment]
Sure, the information will be displayed in MindTagger, I agree that's important. For the reasons above, however, I think it's better to split the fields. From the technical perspective, we're breaking all normal forms with non-atomic fields.

**Comment by ajratner** [comment]
Agreed this makes sense. Will be a slight annoyance to push this change but
nothing fundamentally difficult as far as I see, and better for long run
