### ISSUE TITLE
G: Add some targeted distant supervision rules

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#17]
Example ideas:
- "signs of G", "symptoms of G" [neg]
- "G pathway" [neg]

**Comment by amwenger** [comment]
Do you have any concrete examples of these patterns?

**Comment by ajratner** [comment]
The patterns in the first bullet point came up during a mindtagger session (I can look them up later), the second bullet pt Johannes mentioned- I think he has a bunch.  This would be good to discuss on thursday though

**Comment by Colossus** [comment]
well first I'm actually running the gene extraction/learning/inference pipeline again and mindtagging to find out what changed. our feature change for gene inference probably changed a huge amount.

**Comment by ajratner** [comment]
@amwenger For reference we just decided to try leaving the WORD_SEQ / LEMMA_SEQ features in that we had earlier removed.  This more properly reflects our precision dataset goals at the moment I believe- as any overfitting on these features would just improve precision at the cost of recall

Additionally, as @Colossus pointed out, given our high confidence in the coverage of our gene dictionary, it is sensible to work backwards from this point: i.e. we start with overfitting on gene dictionary matching, then add neg. supervision rules in order to deal with gene names which collide with e.g. english words...

**Comment by amwenger** [comment]
@ajratner @Colossus No objection here.  Thanks for the explanation.

**Comment by Colossus** [comment]
superseded by acronym extraction + simple rules
