### ISSUE TITLE
Fix noncanonical genes names bug!

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#172]
It appears there's one more thing holding back noncanonical gene names, fix this

**Comment by Colossus** [comment]
I think the gene names table was not being fully loaded because of some config option

**Comment by gbgbg** [comment]
Not sure how you came by this but in theory this is one think I hoped dashboard would expose. It'd say total number of genes N1 and we'd say hey, ain't we feeding it a raw table of size N2>N1.
-Gill
