### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by senwu** [ajratner/dd-genomics#174]
(I have already deleted all duplicates in the sentences table)
When I ran this extractor:

```
    deepdive.extraction.extractors.extraction_rule_26 {
      input: """ SELECT R0.doc_id AS "sentences_input.R0.doc_id", R0.section_id AS "sentences_input.R0.section_id", R0.sent_id AS "sentences_input.R0.sent_id", R0.words AS "sentences_input.R0.words", R0.lemmas AS "sentences_input.R0.lemmas", R0.poses AS "sentences_input.R0.poses", R0.ners AS "sentences_input.R0.ners", R0.dep_paths AS "sentences_input.R0.dep_paths", R0.dep_parents AS "sentences_input.R0.dep_parents", R1.mention_id AS "gene_mentions.R1.mention_id", R1.supertype AS "gene_mentions.R1.supertype", ARRAY_TO_STRING(R1.wordidxs, '|^|') AS column_11
    FROM sentences_input R0, gene_mentions R1
    WHERE R1.doc_id = R0.doc_id  AND R1.section_id = R0.section_id  AND R1.sent_id = R0.sent_id
      """
      output_relation: "gene_features"
      udf: ${APP_HOME}"/code/gene_extract_features.py"
      style: "tsv_extractor"
      dependencies: [ "extraction_rule_12" ,  "extraction_rule_24" ]
      input_batch_size: ${INPUT_BATCH_SIZE}
      parallelism: ${PARALLELISM}
    }
```

I got this error:

17:25:42 [extractorRunner-extraction_rule_26] DEBUG Temporary UDF file saved to /lfs/raiders3/1/senwu/deepdive/app/dd-genomics/run/20150902/171324.743472061/tmp/exec_parallel_udf.sh
17:25:42 [Helpers$(akka://deepdive)] INFO  Executing command: "/lfs/raiders3/1/senwu/deepdive/app/dd-genomics/run/20150902/171324.743472061/tmp/exec_parallel_udf.sh"
17:26:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:27:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:28:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:29:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:30:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:31:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:32:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:33:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:33:37 [Helpers$(akka://deepdive)] INFO  Traceback (most recent call last):
17:33:37 [Helpers$(akka://deepdive)] INFO    File "app_main.py", line 51, in run_toplevel
17:33:37 [Helpers$(akka://deepdive)] INFO    File "/lfs/local/1/senwu/deepdive/app/dd-genomics/code/gene_extract_features.py", line 58, in <module>
17:33:37 [Helpers$(akka://deepdive)] INFO      util.run_main_tsv(row_parser=parser.parse_tsv_row, row_fn=get_features_for_row)
17:33:37 [Helpers$(akka://deepdive)] INFO    File "/lfs/local/1/senwu/deepdive/app/dd-genomics/code/extractor_util.py", line 183, in run_main_tsv
17:33:37 [Helpers$(akka://deepdive)] INFO      lines_out += row_fn(row)
17:33:37 [Helpers$(akka://deepdive)] INFO    File "/lfs/local/1/senwu/deepdive/app/dd-genomics/code/gene_extract_features.py", line 38, in get_features_for_row
17:33:37 [Helpers$(akka://deepdive)] INFO      generic_features = [f._replace(name=feat) for feat in ddlib.get_generic_features_mention(sentence, span)]
17:33:37 [Helpers$(akka://deepdive)] INFO    File "/afs/cs.stanford.edu/u/senwu/local/lib/python/ddlib/gen_feats.py", line 82, in get_generic_features_mention
17:33:37 [Helpers$(akka://deepdive)] INFO      if sentence[span.begin_word_id].word[0].isupper():
17:33:37 [Helpers$(akka://deepdive)] INFO  IndexError: string index out of range
17:34:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:35:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:36:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:37:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:38:30 [taskManager] INFO  Memory usage: 205/1963MB (max: 27234MB)
17:39:13 [extractorRunner-extraction_rule_26] ERROR java.lang.RuntimeException: Failure when executing script: /lfs/raiders3/1/senwu/deepdive/app/dd-genomics/run/20150902/171324.743472061/tmp/exec_parallel_udf.sh
17:39:13 [profiler] DEBUG ending report_id=extraction_rule_26

**Comment by Colossus** [comment]
Hey @SenWu , I fixed this error on Monday. This had to do with the way the sentences were extracted in extractor_util.py. Could you pull and try again? Or did you just pull, and I introduced an error accidentally?

**Comment by Colossus** [comment]
@SenWu if you actually pulled and it turns out I introduced an error instead of eliminating it, please try working from 380e071f9a16d5dc281a6ebf0643eb7c55129fed .

**Comment by Colossus** [comment]
Sen, is this fixed?

**Comment by chrismre** [comment]
@SenWu +1 @zhangce

**Comment by senwu** [comment]
Yes, it works in the https://github.com/HazyResearch/dd-genomics/commit/380e071f9a16d5dc281a6ebf0643eb7c55129fed. Sorry for the late response.
