### ISSUE TITLE
With noncanonical genes, gene supervision completely thrown off by random English words

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#175]
A few random lines from the genes table are FULL of "for", "was" etc.

I think the problem can be solved very simply by now making a distinction between all-uppercase and upper/lower case matching when discovering genes. I think this is better in general. For canonical gene names, we didn't have English clashes regardless of case; as it turns out we have clashes for noncanonical gene names (REFSEQ IDs hardly occur at all, apparently), we'll require case sensitivity and see if this fixes stuff.

**Comment by amwenger** [comment]
In the future, you might also consider keeping italicized words with an initial capital to be more sensitive to mouse gene name mentions.  By [convention](https://en.wikipedia.org/wiki/Gene_nomenclature):

| Species | Gene | Protein |
| --- | --- | --- |
| Human | uppercase italics (e.g. _SHH_) | uppercase (e.g. SHH) |
| Mouse | initial capital italics (e.g. _Shh_) | uppercase (e.g. SHH) |
| Zebrafish | lowercase italics (e.g. _shh_) | initial capital (e.g. shh) |

**Comment by chrismre** [comment]
@zhangce @ajratner We need to retain font faces... Do we have this info reliably?

**Comment by Colossus** [comment]
@chrismre I think currently both boldface and italics are marked by underscores left and right of the word. 

@amwenger There are two issues with this: 1) not everyone italicizes gene names 2) this has been in the back of @ajratner 's and my heads for a long time, but we didn't get around to it ...

**Comment by ajratner** [comment]
This is currently picked up by the XML parser and converted to markdown
style- seems to be present for PMC-OA but not Pubmed abstracts

**Comment by zhangce** [comment]
> > seems to be present for PMC-OA but not Pubmed abstracts

If we really need this, we should be able to get this from the html version
of the Pubmed abstract dump.

Ce

**Comment by amwenger** [comment]
I agree that sticking to uppercase is good for now.  Lucky for us, the human gene and protein conventions are both uppercase.

**Comment by gbgbg** [comment]
Sorry to be do daft. Can you remind me why this is an issue at all? The (human) gene world is a closed world. Only names and acronyms provided by us can be real human gene names (some mentions will, some mentions won't). But any mention of a word not in the finite gene list (like was, for) cannot be true. 
Are we trying to discover gene names  or synonyms unknown to us?
If we do not, but DD cannot be stopped from looking for new names / acronyms, isn't there a place where we can curtail these efforts?
There must be something fundamental I'm missing / forgetting.

**Comment by Colossus** [comment]
The noncanonical gene name list simply contains the words "for" and "was" and perhaps a few other common words. 

(I just discovered WAS is actually a canonical symbol ... however, it didn't cause problems so far. Maybe "was" is actually not that common a word in bio literature, but "for" definitely is.)
