### ISSUE TITLE
G: Get rid of certain 'bad' gene names

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#18]
Is this about resurrecting `bad_genes.tsv`, or (more ideally) are there specific distant supervision rules we can add and/or some systematic errors in our gene-list generation step?

**Comment by Colossus** [comment]
w/r/t "SPATIAL", which actually triggered this: Spatial is actually a gene. It is better known as TBATA.

**Comment by ajratner** [comment]
@Colossus we do have a list of english words to check genes against & at very least handle this in a specific way

**Comment by Colossus** [comment]
reopen if comes up again
