### ISSUE TITLE
Loading of gene features has taken 24 hours so far and is 36% done

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#188]
- Trying PARALLEL_LOADING=true
- trying inference.parallel_loading: ${PARALLEL_LOADING}

I'm not going to wait for weeks. It's slightly ridiculous; raiders2 is sitting there with 1 CPU at 60% load, disk mostly idle and twiddling its thumbs while each of the few billion rows is being carefully inspected and then being orderly inserted into the gene_features table. It reminds you of Stanford's post office.

**Comment by ajratner** [comment]
@Colossus Is this issue still open?  See my email comment about trying a fresh install of GP on one of your machines, any other ideas in the pipeline...?

**Comment by Colossus** [comment]
We can maybe close this; the thing is, I'm now loading the gene features WITH gpfdist and it's already running for more than 24 hours. Without GPFdist, I could at least check on progress, because the new lines were apparently committed regularly ... however, GPFdist apparently makes a whole giant transaction out of the data loading process, and I have no idea how many lines have already been loaded, just hope that it's going to finish at some point. ... I really don't know what to do. 

Writing the whole gene mentions table to disk and even running the gene features UDF takes only 4 hours, which is a fraction of the time that's just needed to write the friggin UDF output into a stupid database table. I'm really not sure what's happening there.

One theory is that GreenPlum in good old database fashion is logging every line to disk etc. etc. and making really sure everything is crash-protected in the annoying way databases do stuff ... at this point I just wonder if we should take all seat belts off and drive headlong into traffic. If I knew how to do it, I would do it.

**Comment by Colossus** [comment]
As in, setting all database settings to read uncommitted, turning off logs, setting read and write buffers to max and whatever we can do to make it load these friggin gigabytes faster. I mean, it's not the world. Why is it taking over a day to load a few GB worth of stupid lines into a table, for Alan Turing's sake?

**Comment by Colossus** [comment]
Like 300 GB, actually.

**Comment by Colossus** [comment]
Or we could cut down the feature set drastically. Which would also increase loading speed.

**Comment by Colossus** [comment]
... input is welcome ;)

**Comment by ajratner** [comment]
@Colossus So my head's been elsewhere a bit (CS145 prep + family visiting last week)- could you recap the time line of when / what started these speed issues for me quickly?

To what degree is this because of changes (i.e. acronyms, correct?) and to what degree are we unsure of the cause, in your estimate?  The actual raw dataset size hasn't increased that much correct?  And has the gene feature set actually increased that much (over when it was running in a sane amount of time) with the new changes you added?

**Comment by ajratner** [comment]
Just focusing on gene features for instance: when I ran the full set this was slow and occasionally crashed randomly, but nowhere near this slow.  Has it really increased that much?  Why exactly?

**Comment by Colossus** [comment]
There are two reasons for the slowdown:
- 1 (For sure this is happening): With noncanonical gene names, we have a giant increase in the number of gene mentions that we pick up. I don't exactly know how much, but at least 3 times as much.
- 2 (This might be an additional reason, but I hope it's not): I added a bunch of indices to most tables (on doc_id, section_id, sent_id) to make some extremely slow joins faster. I think up to now most joins just did a sort of the whole table ...

it's a tragedy. I don't know how long this excruciating loading process will continue. If I knew it was done in an hour, I'm not going to stop it now. If I knew it was going to take one more week, I'd stop it now. I already crashed it yesterday and tried with a 50,000 docs subset, which loaded pretty fine. THen obviously I had to restart the whole process, including dumping to disk and re-running the UDF, at which point I really wished there was a way to tell it not to re-run the UDF etc ...

**Comment by Colossus** [comment]
So I don't know what to do. One way to go forward is to kill the run, try with 100,000 docs then 200,000 docs then 1,000,000 docs and see how it scales. And try with indices and without.

I'd almost compromise on this (because I have other stuff to do now) and see if it's loaded tomorrow morning. If it isn't I'm just gonna kill it and test the scaling first. Which I should maybe have done beforehand; only until this point we never had serious performance problems (longer than a few hours). And I thought parallel loading would fix this crap. But it doesn't.

**Comment by ajratner** [comment]
So since there's no time pressure coming from our end re: a day difference- I'm not blocking on you or anything- I'd say letting it run and checking in the AM sounds good

However a scaling analysis- start even smaller than 100k probably (10K?)- seems like it would be very helpful as a first step re: deciding e.g. could we just thin out features a bit, etc?

If a small number of docs hangs as well, we have a different sort of problem than if it runs but slowly, and making this distinction should help us debug...

**Comment by ajratner** [comment]
One other thing I'd add is that we could have a brainstorming session with you, me, and some others in the lab who know more about this sort of stuff / have more experience debugging such things.

One issue is that a lot of these guys are under some intense pressure from MEMEX for the next week or so... but even just to give you a break from hammering on this on your own, even if not too helpful, let me know?

**Comment by ajratner** [comment]
Also could we test on a tiny (10K) set versus the old version of code that did run on the full set in reasonable time (e.g. without noncanonical) just to compare various numbers between them, maybe give us some insight on what changed the most?

**Comment by Colossus** [comment]
Hammering is fine. BTW I tried with 50k docs and it loaded fine. So the next step would be 100k docs I guess.

**Comment by Colossus** [comment]
Argh I'm an idiot ... The 50k run I apparently stopped after gene_mentions, not gene_features ... oh man oh man. I'm still going to try UNTIL tomorrow morning. If I get started on this now, I'll not be in bed until 3am and the only effect will be that I'm behind on my CS273a presentations and my sleep schedule is FUBAR

**Comment by Colossus** [comment]
EDIT upstairs: meant "not going to try UNTIL tomorrow"

**Comment by ajratner** [comment]
Sounds like a plan- I think your time would be best spent making/finding
more of those halloween-themed slides anyway haha :)

Yeah so maybe, whenever you get around to it, try 10K on gene_features, and
maybe also try 10K on old version of the code gene_features to compare?
Let me know if you want to meet up and chat too (maybe next week?)

-Alex

**Comment by Colossus** [comment]
K sounds good!

**Comment by amwenger** [comment]
It's definitely worthwhile to try without indices.  In my experience (admittedly with MySQL and DB2 not PostgreSQL or Greenplum), bulk loading is much slower with an index.  You could split the process into two stages: first to load the data, then to create the indices.

Also, do you know if DeepDive uses pgsql COPY or a series of INSERTs.  COPY is of course much faster.

See general tips on [PostgreSQL bulk loading](http://www.postgresql.org/docs/9.4/static/populate.html).

**Comment by ajratner** [comment]
I am fairly certain that deepdive uses COPY + no index, but you're right we
should double check that no settings got changed somehow, might as well?

**Comment by Colossus** [comment]
Hey Aaron, thanks for the input. I'm basically positive that GP uses COPY. In fact, the details are as follows:
- When parallel loading is disabled, it uses COPY, I know that for sure. From looking at the logs and the commands that are output from `select * from pg_stat_activity`.
- With parallel loading, I think GreenPlum is doing its own magic that might neither be copy nor INSERT, but I'm fairly sure it should actually be reasonably fast.

**Comment by Colossus** [comment]
OK, it was still not finished, so I killed the run. I'm now going to do the scaling test with and without indices.

**Comment by ajratner** [comment]
Sounds great let me know how it turns out

**Comment by raphaelhoffmann** [comment]
Not sure if this is relevant here, but the last couple of times when I
experienced a similar problem it was due to one of the following:
- There must be some upper limit on the time that your session remains
  connected to the Stanford server hosting the home directories. When you
  quit your long-running job and you can't run "touch ~/test", then you know
  that you have been disconnected.
- If the disk is too full, it might be fragmented. This is why
  /lfs/local/0 on raiders4 is pretty much unusable now, but /lfs/local/1
  works fine.

**Comment by Colossus** [comment]
Interesting. Because we're mostly on /lfs/local/0 on raiders2 currently.
I think the database is also on there.

**Comment by Colossus** [comment]
Can we defragment the thing in some way?
