### ISSUE TITLE
The (1) COPY TO STDOUT; (2) UDF; (3) COPY FROM STDIN stages should be made separately runnable

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#189]
If memory/HD/whatever runs out during the UDF or during COPY FROM STDIN, all previous stages are wasted when re-running one particular extractor. It would be awesome if COPY FROM STDIN could be invoked explicitly without STDOUT or UDF.

**Comment by ajratner** [comment]
@Colossus So we can do this in a hackey way obviously... but for a more integrated approach, maybe post as a deepdive issue?

**Comment by Colossus** [comment]
I know, I created a whole bunch of issues in our own thread that I just
want to discuss first before spamming the DD issues list. After doing
that, we can close all of these.

**Comment by ajratner** [comment]
Sounds good!

**Comment by Colossus** [comment]
This is fixed by the latest ddlog
