### ISSUE TITLE
Get variants working again for real

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#199]

**Comment by ajratner** [comment]
@Colossus at some point when back in the swing of things (maybe at our next "AM hackathon") let's discuss in person?  Am curious if you have new thoughts here or this is referencing the short-run / simpler solution we'd discussed...?

**Comment by Colossus** [comment]
No, I was gonna do it more or less properly, with inference and stuff. First variant, then gene-variant, then gene-variant-pheno

**Comment by ajratner** [comment]
Nice, ok very cool
