### ISSUE TITLE
G: Add in Generifs dataset for additional supervision?

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#20]

**Comment by Colossus** [comment]
Want to bump this again. This might get us a high precision gene set.

**Comment by Colossus** [comment]
Proposed way of action: Pre-label the generifs dataset with doc_id (already there), section and sent_id by a separate extractor. Then load generifs into a database table and distant supervision based on generifs should be a single UPDATE query.

**Comment by ajratner** [comment]
This sounds good! Regarding the update query- how will it look when we run
from start- should we try to integrate into normal Distant supervision /
feature extraction pipeline with eg something pretended to distinguish
generif doc ids... Or keep separate?

I'm a priori in favor of doing all in one pipeline and just identifying
generifs as separate via id tag or something, but could be convinced either
way

**Comment by Colossus** [comment]
gene precision is not a problem anymore
