### ISSUE TITLE
Add gene acronym filtering via linear logic again

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#204]
Currently gene acronyms are hard removed from the gene mentions table

**Comment by Colossus** [comment]
Not sure if we actually need this --- I kinda want to discuss gene acronyms for distant supervision

**Comment by gbgbg** [comment]
But you didn't bring it up in Monday ...
I generally suggest making a list of items to discuss, that grows through the week (eg a note on your phone) and coming with this list to the all hands meeting

**Comment by Colossus** [comment]
I didn't bring it up because (a) I brought it up a week ago, when I said "it works great, but it might not be in the latest development branch" and Chris said "you should have a second look, perhaps it's actually in there" and (b) because I want to use the gene acronym tagger for distant supervision now, as was discussed on Monday, and this is mutually exclusive with linear logic
