### ISSUE TITLE
2-19 is a gene name; require at least one letter in a gene name

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#209]

**Comment by amwenger** [comment]
My memory was off, I thought the nonsense gene mention was from a sentence about Chinese children ages 2-18.  In fact, it is about Japanese children ages 2-19.  The details are:

PMID 22806002
Abstract sentence 2
Gene: ENSG00000071889 (known as FAM3A, 2-19, DXS560S, or XAP-7)
Phenotype: HP:0000729 (Autistic behavior)

> Subsequently , to assess the discriminant and diagnostic validity of ADI-R-JV , the authors investigated 317 individuals aged **2-19** years , who were divided into three diagnostic groups as follows : autistic disorder ( AD ) , pervasive developmental disorder not otherwise specified , and other psychiatric diagnosis or no diagnosis , according to the consensus clinical diagnosis.

**I recommend to remove any non-canonical gene names that do not include at least one letter.**

**Comment by Colossus** [comment]
This is fixed.
