### ISSUE TITLE
Genes are extracted only from sentences where phenos are present

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#211]
This is currently happening. Not too sure where to put this, but it must remain a running task to update this extractor whenever we need genes from OTHER documents as well. Particularly after extracting variants, for gene-variant, we should make sure to include all doc_ids from variant_mentions as well.

**Comment by ajratner** [comment]
We used to have a google document where we kept track of "hacks" I think?

Currently the hacks are mostly either aggregated in the config file- e.g. hard filters in candidate extraction stage, etc.- or are present for efficiency reasons in the application.conf / app.ddlog file, like this one.  So perhaps that's good enough, but we could also think of keeping a list
