### ISSUE TITLE
Next parser run: switch back to doc_id and sent_id as keys

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#213]
sent_id should be always increasing; we want to keep doc_id and section_id, but section_id is not part of the key. (Additionally, paragraphs ...)

**Comment by ajratner** [comment]
@Colossus we might want to specifically know which sentence is the _first_ one in a section, as leading sentences are sometimes important..?

Is there a specific reason to do this other than simplicity?

**Comment by Colossus** [comment]
Yeah, for all kinds of stuff it's useful to know that a mention occurred before or in a sentence. E.g., acronym resolution in sentence 300 is typically only useful if the acronym was defined in some sentence <= 300. With the current scheme, this would require some logic and is hard to encode in a SQL query.

About the "first sentence index": this should be trivial by, e.g., 

```
select doc_id, section_id, min(sent_id) from blah group by doc_id, section_id;
```

**Comment by Colossus** [comment]
In particular, its useful for variants: I doubt there are many instances where a variant is described in a sentence before the gene is first named in a document. Using such a simple scheme, we could maybe downsize the number of variant-gene pairs throughout a document significantly.

**Comment by Colossus** [comment]
This will never happen, there's too much stuff around it
