### ISSUE TITLE
genes-per-name unexpected duplicates(!)

### ISSUE THREAD

**Issue by gbgbg** [ajratner/dd-genomics#216]
Snapshot 20151015-4
- surprising entry:
  ENSG00000278848 {TP53TG3D,TP53TG3,TP53TG3C,TP53TG3B}    4
  how can an ensembl gene id map to more than one gene locus?

http://uswest.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000278848;r=16:33459045-33462249;redirect=no
suggests this gene is NOT TP53 but rather some weird (non coding RNA?) called RP11-23E10.6 

Something is not right here..

And by extension with all ENSG that map to more than one gene I would think. I see another P53 weirdo:

ENSG00000275034 {TP53TG3D,TP53TG3,TP53TG3B,TP53TG3C}    4
- similarly what's up with

NM_001017436    {CT45A9,CT45A2,CT45A8}  3

NCBI via google says its neither of these three but CT45A4
http://www.ncbi.nlm.nih.gov/nuccore/NM_001017436.1

I would check the above two NOT because I care about these two genes -- I'd do it to make sure no bigger bug lurks within.
- What's up with

TP53TG3B    {TP53TG3B,TP53TG3B,TP53TG3B}    3

all three names seem identical...

Similarly 

TP53TG3 {TP53TG3,TP53TG3,TP53TG3}   3

and a bunch other P53 entries
- You have similar non P53 things

ZFP41   {ZFP41,ZFP41}   2
TAFII31 {TAF9,TAF9} 2

Get the idea ... You can query for others..

My guess is our base dictionary is not clean.
Maybe a minor issue, maybe not so minor.

**Comment by Colossus** [comment]
Gill, it is time to invoke Dr. OED in this instance, because "duplicity" for "duplicate" is poor usage: 

duplicity, n: 1. The quality of being ‘double’ in action or conduct (see double adj.1 5); the character or practice of acting in two ways at different times, or openly and secretly; **deceitfulness, double-dealing**. (The earliest and still the most usual sense.)

http://www.oed.com/view/Entry/58600

**Comment by amwenger** [comment]
I've learned over the years not to be offended by Gill's accusations of
duplicity. He doesn't mean it.

**Comment by gbgbg** [comment]
I most certainly do not. I will try to root it out.
I did manage gauge and gouge. But not this one.
