### ISSUE TITLE
More rules targeting gene expression

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#229]
There are tons of sentences that tell us that certain diseases come with specific gene expression patterns. We're not interested in those.

Among the sentences are gems like this one:
"In the Looi et al. study on ocular MCL, CD5 was negative in thirty percent of the cases, which is less often seen in patients with nodal MCL."

Another example:
"The differences reached significance ( p ≤ 0.05 ) for seven of these ten quantified genes , with CXCL3 , CXCL6 , and COL2A1 being elevated in the femoroacetabular impingement group compared with only the control group and IL-8 , CCL3L1 , ADAMTS-4 , and ACAN being elevated compared with both the osteoarthritis and control groups ."

**Comment by Colossus** [comment]
" In comparison with the colon cancer
colon cancer cell lines incubated in 5 % CO ( 2 ) only , the invasive ability of cells increased in all the colon cancer cell lines subjected to incubation in 20 % CO ( 2 ) followed by incubation in 5 % CO ( 2 ) , with a concomitant increase in the mRNA expressions of matrix metalloproteinase-2 ( MMP2 ) and MMP9 . "

**Comment by Colossus** [comment]
" Recently , it has been demonstrated that LIF overexpression results in moderate splenomegaly and slightly activated extramedullary hematopoiesis . "

**Comment by Colossus** [comment]
" To characterize the role of HAS2 expression by myofibroblasts in the pathogenesis of pulmonary fibrosis , we evaluated transgenic mice with targeted human HAS2 expression in ASMA-expressing cells . "

**Comment by Colossus** [comment]
The word "concentration" is a sentence is highly associated with a wrong fact.

**Comment by Colossus** [comment]
" As illustrated in , the mRNA level of WT1 was significantly overexpressed in NSCLC specimens ( *\* p < 0.001 ) . " (NSCLC = non-small lung cell carcinoma)

**Comment by Colossus** [comment]
Guys, there's a "rumor-suppressor gene".

" We used the flow cytometric immunoassay to study the correlation between the rumor-suppressor gene product p53 - and the DNA ploidy in 30 de novo cases of acute nonlymphocytic leukemia ( ANLL "

**Comment by Colossus** [comment]
"     Increased TNFα and MCP-1 expression can promote breast cancer progression , through direct binging to the TNF receptor and through recruitment of macrophages to tumor sites , respectively ( , ) . "

**Comment by Colossus** [comment]
" CUL4A amplification or overexpression has been reported in some human cancers , including breast cancer , squamous cell carcinoma , adrenocortical carcinoma , childhood medulloblastoma , prostate cancer and hepatocellular carcinoma and is associated with poor prognosis in node-negative breast cancer ( -- ) . "

**Comment by gbgbg** [comment]
Specific to correlations. 
You may want to take this with @amwenger. I was always in favor of going after causation first and foremost. Do not let correlations dominate your day is my 2c.

**Comment by Colossus** [comment]
This is not specific to correlation. Why do you think so? It is just as important to supervise these sentences false for causation as for association candidates. Meaning: If we hadn't gone for association in the first place, then this issue would still be here.
