### ISSUE TITLE
P: Get rid of some bad phenos still showing up e.g. "chronic"

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#24]
Should be some sub-tree of the HPO DAG to eliminate (didn't we already do this?)

**Comment by amwenger** [comment]
The term "chronic" (HP:0011010) is a descendant of "Clinical Modifier" (HP:0012823).  We should limit to descendants of "Phenotypic abnormality" (HP:0000118).

Check out http://compbio.charite.de/phenexplorer/ for a decent tool for exploring HPO.  The "ontology" tab lets you browse the ontology structure.

**Comment by ajratner** [comment]
Ok- so we / Robin did do the subtree pruning.   It was actually an error in one of our source files.

In the file we get from Charite, `HP:0002582: Chronic atrophic gastritis` has a reference ("xref") to the MeSH entry for "Chronic", which in a post-processing script we add as a synonym.  I looked and it seems like these "xref" fields don't add much- they are either the same name as the HPO term, one of its synonyms, or erroneous (as in this case), so I just took this step out

For reference: our process is that we take in some file from compbio.charite.de- `onto/raw/hpo.obo`\- which we then parse using `onto/parse_hpo.py -> onto/data/hpo_phenotypes.tsv`; then, before every run of `pheno_extract_candidates` we run _another_ preprocessing script which outputs to `pheno_terms.tsv`

Clearly this processing should be simplified, but I think we'll accomplish this when we add UMLS #10

**Comment by ajratner** [comment]
Note @Colossus that the script needs to be rerun; instead of rerunning everything in `make_all.sh` just do: `cd onto && rm data/hpo_phenotypes.tsv && python parse_hpo.py raw/hpo.obo data/hpo_phenotypes.tsv`

**Comment by Colossus** [comment]
@ajratner I get: rm: cannot remove `data/hpo_phenotypes.tsv': No such file or directory and the file is not created afterwards

**Comment by ajratner** [comment]
@Colossus  That's odd, I would think it would have been there- have you ever run the
pheno extractor from your repo?  If so this file would need to be there, or
else an error should have been thrown, or else something else going on...

Either way, just don't remove it, run the python script to create it
