### ISSUE TITLE
Move serialize_genepheno_pairs_split into ddlog

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#248]
I think the corpus is currently so small that it won't cause any memory errors.

After Jaeho moves us to Postgres and saves us from GreenPlum for the rest of our short lives we're never gonna need this again

**Comment by ThomasPalomares** [comment]
done in  commit https://github.com/HazyResearch/dd-genomics/commit/cf74f1591ae6b4307a79494424a1bd130d743f0a
