### ISSUE TITLE
Error with adding items to iterate set in create_allowed_phenos_list.py?

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#249]
This was throwing me an error since the size of a set being iterated over was getting changed... I fixed it in most minimal way possible (+ `.copy()`) however I'm confused as to why this hadn't happened to anyone else... any ideas?

Also this could probably be cleaned up by folding into `data_util.get_hpo_phenos`, but not high priority

**Comment by Colossus** [comment]
I've never had this, no idea where it's coming from
