### ISSUE TITLE
GP: Can we use NHGRI GWAS catalogue / other similar datasets?

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#25]
For supervision re: the causal vs. associative division?

**Comment by amwenger** [comment]
Good idea.  Also check out [GWASdb2](http://jjwanglab.org/gwasdb), which has a much larger set than the GWAS Catalog.  The GWAS Catalog includes associations with p-value < 1e-5 from studies that examined at least 100,000 SNPs; GWASdb2 includes SNPs with margin p-values < 1e-3.  GWAS Catalog has about 20,000 records; GWASdb2 has about 250,000.
