### ISSUE TITLE
False positive genepheno causations classification

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#258]
3/5 contain a gene mention that's not a gene. Increase G precision alone! 4/5 contain the sentences structure "(disease) characterized by PHENO". 1/5 is actually an edge case and depends on wording, it says "PHENO linked to GENE". If "linked to" means causation, I'll buy it as a positive.

**Comment by ajratner** [comment]
These are some good targets for DSRs seems like!

**Comment by Colossus** [comment]
well yes and no. I'd first say these are good targets for gene precision increase. I wouldn't supervise based on "characterized by" ... this could be actual GP causation too ...
