### ISSUE TITLE
Eval pipeline is documented, but can probably be simplified

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#262]
Check out the README, should be straight forward- let's get labeling!

However we can probably still make some simplifications to reduce friction in the process (i.e.: write shell wrappers around the wrappers, for now...)

@ThomasPalomares @youssefahres

**Comment by shayanzare007** [comment]
Labeling pipeline automated on youssef-pheno branch:
Finished testing and README.

Still need to update the compute_stats.sh to get it to work with the new pipeline
