### ISSUE TITLE
Create Views for util evaluation scripts

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#264]
util/gene_holdout_stats.sh etc

**Comment by Colossus** [comment]
(source ../env_local.sh; ./gp_holdout_fp_caus_sentences.sh genomics_jbirgmei_2)

**Comment by Colossus** [comment]
Please add features as well; I didn't care previously

**Comment by ajratner** [comment]
+1

**Comment by ThomasPalomares** [comment]
This was actually done in #278 and #272.
