### ISSUE TITLE
Automatically withhold holdout set from pipeline

### ISSUE THREAD

**Issue by shayanzare007** [ajratner/dd-genomics#271]
we should clean this up so it happens automatically

**Comment by Colossus** [comment]
So it's not like the manually labelled stuff flows into the pipeline. If anything, we can rule "don't distantly supervise relationship candidates that are in the current holdout set".

**Comment by Colossus** [comment]
Withholding the whole holdout set from the "pipeline" means that nothing goes through the candidate or inference pipeline

**Comment by Colossus** [comment]
I'm gonna take care of this now

**Comment by Colossus** [comment]
Gotta learn to write some ddlog

**Comment by shayanzare007** [comment]
Yes, let's wait until the pipeline is integrated: it all works and ready for pull request. i'm not getting the same numbers for precision and recall at all. I debugged it and the pipeline seems to work fine. Let's figure it out as soon as we sit down together

**Comment by shayanzare007** [comment]
Also, we can do this now because the DB for labels is there and already populated. So, just need to import it to DD DB (3 lines on shell)

**Comment by Colossus** [comment]
OK sounds good. Are you still getting super low precision?

**Comment by Colossus** [comment]
If that's the case, are you sure you have FP defined as DD expectation > 0.9 and label is 'false'?

**Comment by shayanzare007** [comment]
Yes, I checked a dozen examples to that end. Ideally, all the team should try to switch to my branch and compute stats from there on their DD tables 
Otherwise, we can discuss it today over/after the lab lunch. I can explain exactly what I did. It might be a workflow error..

**Comment by Colossus** [comment]
OK I'll come to lab lunch maybe. I hate it though. Could we maybe meet at 1 or so? I really want to avoid the frenzy. It suddenly feels as if we weren't doing anything special and extraordinary after all

**Comment by Colossus** [comment]
Actually, good thing. The Bej Lab is invited to a different lab's lab meeting/lab lunch. So I can't come to the DD lunch, thank god. I'd love to meet afterwards if possible. Maybe I can't make 1pm sharp

**Comment by shayanzare007** [comment]
1pm sharp sounds good! I have a meeting at 2:15, should be way enough! See you then

**Comment by Colossus** [comment]
well maybe I can't be there 1pm sharp because my other lunch is till 1. Let's do 1:10; or please just gimme a few minutes

**Comment by shayanzare007** [comment]
Of course, no worries

**Comment by ThomasPalomares** [comment]
Added to ddlog from Youssef's import_labels.sh script in c08e4eeb0ff7b7cfec90f10618b84ef9e26a9962

**Comment by shayanzare007** [comment]
Cool, thanks Thomas for translating to DDLog. To close the issue, we still need to withhold the sets that are in gene_labels/pheno_labels/genepheno_causation_labels/genepheno_association_labels from being "distant supervised"

**Comment by ajratner** [comment]
Cool, glad to hear this is in ddlog!

We should definitely prioritize making this bit clean, that way we can
isolate whether this is a factor in the variance around precision/recall
numbers first thing tomorrow when we meet

**Comment by Colossus** [comment]
the code for that is on master now; just cleaning it up a little

**Comment by Colossus** [comment]
sorry I introduced an error into app.ddlog here. Just fixing it
