### ISSUE TITLE
Multiple P candidates for multi-word phenotypes being made

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#288]
For ex, see:

``` sql
SELECT gene_wordidxs, pheno_wordidxs
FROM genepheno_causation
WHERE doc_id = '20142852' AND section_id = 'Body.0' AND sent_id = 107;
```

At one point I remember adding code in the pheno extractor to make sure that for any span of words, we only ultimately took one phenotype candidate (the longest match).  @Colossus did this get removed, or is this a bug?

@youssefahres Something to look into & think about?  The heuristic of only keeping the longest match may not be the best idea; but what's happening now, with multiple matches, seems like it will bias weights learned towards examples with longer phenotype phrases...

**Comment by Colossus** [comment]
I'm not sure what happens there --- I wanted to look into the pheno extractor for our recall issues anyways today, thanks for alerting

**Comment by Colossus** [comment]
two different phenos getting picked up here:

```
SELECT gene_wordidxs, pheno_wordidxs, pheno_entity, names
FROM genepheno_causation c join allowed_phenos p on (c.pheno_entity = p.hpo_id)        WHERE  doc_id = '20142852' AND section_id = 'Body.0' AND sent_id = 107;
 gene_wordidxs |   pheno_wordidxs    | pheno_entity |            names
---------------+---------------------+--------------+------------------------------
 {18}          | {34,35,36,37,38}    | HP:0009129   | Upper limb amyotrophy
 {18}          | {33,34,35,36,37,38} | HP:0007149   | Distal upper limb amyotrophy
```

Maybe we should only take the lowest phenos from the DAG, HP:0007149 is a descendant of HP:0009129 (didn't look it up, but almost for sure) ... but OTOH it's not too much of an issue; in the output we were going to canonicalize over the pheno DAG anyways, so why bother
