### ISSUE TITLE
Create more evaluation scripts showing false positive/true positive sentences along with information

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#289]
Should print out for each FP/FN/TP/TN:
- doc_id
- section_id
- sent_id
- gene name
- gene wordidx
- pheno words
- pheno wordidxs
- Sentence (space separated, not |^|)
- lemmas of sentence (space separated, not |^|)

**Comment by ThomasPalomares** [comment]
Hey @Colossus , not sure what you want exactly but if it's just the list of TP/FP with these info, they are already in views: when you click on [...] below a certain genepheno, all these info are displayed.

**Comment by shayanzare007** [comment]
@Colossus this will go in the result logs (for reproducibility), rather than summary statistics.

**Comment by shayanzare007** [comment]
This is done already
