### ISSUE TITLE
Incorporate datasets beyond PLoS, PMC and PubMed

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#29]
PM abstracts, science direct, etc... how many of these have XML or clean enough HTML vs. OCR/pdf?

**Comment by amwenger** [comment]
I'd put OMIM on this list.  It has a text file download.

**Comment by ajratner** [comment]
What else?  I think we had a few other crawls from e.g. science direct, etc. floating around.  Chris has mentioned Nature- that we might be able to get some stuff from them... I think Emily (Altman lab) might have some stuff we could use...

One issue here is format- some of these might be in messy / unknown formats.  I think regardless we should proceed in order of decreasing format quality, or some average of this + suspected fact density

Anyway when we get PMC, PubMed & PLoS all in, we should start asking around about this...

**Comment by ajratner** [comment]
Are any of the following of use from the DeepDive OpenDatasets library @amwenger @gbgbg?:
- _Biodiversity Heritage Library_
- _BioMed Central_

**Comment by amwenger** [comment]
The BioMed Central (aka BMC) and PLoS journals are relevant.  Biodiversity Heritage Library is irrelevant.

It seems to me that most leveraged approach it to work with PMC, which has full text of all biomedical open access articles.  That includes all BMC journals and all PLoS journals (from [PMC journal list](http://www.ncbi.nlm.nih.gov/pmc/journals/)).

@ajratner Is there a reason to treat PLoS and BMC as special cases?  Can you simply handle them as part of PMC?

**Comment by gbgbg** [comment]
@ajratner - just fyi, BMC is "the opposite" of PLoS
in PLoS one journal is a clearing house, PLoS ONE, the others are more 
rigorously peer reviewed
In BMC only one journal (that I know of), Genome Biology, is properly 
peer reviewed
There are a number of BMC-X (BMC genomics, BMC bioinformatics, ...) 
journals, and those are not carefully reviewed.

@amwenger- @collosus took a quick look at our PMC dump recently - and 
failed to see there any PNAS - the 2nd most frequent journal in OMIM 
(and he has not looked carefully further down the list of journals, 
AFAIK). Moral: In theory, PMC should subsume all of PLoS and BMC. That's 
great. But does it in practice?

We don't have to resolve it tonight. We're trying to make the most of 
what we have at the moment anyways. Be good to come back to this 
question when we switch back to careful-ramp-up mode, soon.

**Comment by gbgbg** [comment]
@ajratner FYI We've identified quite a few additional worthy sources:
http://dev.stanford.edu/confluence/display/collaborators/Additional+Sources+for+DeepDive+crawling

I wouldn't tackle any tonight. Rather as Johannes and I discussed we 
need a "background" process at some point to acquire more of these. 
Maybe driven by a librarian we hire to feed the beast... (#pipedream)

**Comment by ajratner** [comment]
@gbgbg That I agree would be awesome :)  I know Chris et. al. recently talked at a big librarian's conference, so maybe this could be in the cards to actually happen sometime soon...

My point in the email I just sent is that there's no excuse for the actual _parsing / preprocessing_ of new data sets to require a whole person (given they're in similar XML format say..) if we keep the code clean & the process documented;

but as for someone to go around and hunt down / acquire these new datasets... :)

**Comment by Colossus** [comment]
Not on the horizon
