### ISSUE TITLE
genepheno_relation_ids are not all distinct, fix asap

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#304]

**Comment by Colossus** [comment]
This was probably introduced by our latest change of relation_id

**Comment by Colossus** [comment]
select \* from genepheno_relations where relation_id = '17437132_Body.0_23_31_17437132_Body.0_23_7-8';
 id |                 relation_id                  |  doc_id  | section_id | sent_id |    gene_mention_id    | gene_
name | gene_wordidxs | gene_is_correct |    pheno_mention_id    | pheno_entity | pheno_wordidxs | pheno_is_correct
----+----------------------------------------------+----------+------------+---------+-----------------------+------
-----+---------------+-----------------+------------------------+--------------+----------------+------------------
    | 17437132_Body.0_23_31_17437132_Body.0_23_7-8 | 17437132 | Body.0     |      23 | 17437132_Body.0_23_31 | SDS
     | {31}          | f               | 17437132_Body.0_23_7-8 | HP:0000089   | {7,8}          |
    | 17437132_Body.0_23_31_17437132_Body.0_23_7-8 | 17437132 | Body.0     |      23 | 17437132_Body.0_23_31 | SDS
     | {31}          | f               | 17437132_Body.0_23_7-8 | HP:0000089   | {7,8}          |
    | 17437132_Body.0_23_31_17437132_Body.0_23_7-8 | 17437132 | Body.0     |      23 | 17437132_Body.0_23_31 | SDS
     | {31}          | f               | 17437132_Body.0_23_7-8 | HP:0008678   | {7,8}          |
    | 17437132_Body.0_23_31_17437132_Body.0_23_7-8 | 17437132 | Body.0     |      23 | 17437132_Body.0_23_31 | SDS
     | {31}          | f               | 17437132_Body.0_23_7-8 | HP:0008678   | {7,8}          |
    | 17437132_Body.0_23_31_17437132_Body.0_23_7-8 | 17437132 | Body.0     |      23 | 17437132_Body.0_23_31 | SDS
     | {31}          | f               | 17437132_Body.0_23_7-8 | HP:0012210   | {7,8}          |
    | 17437132_Body.0_23_31_17437132_Body.0_23_7-8 | 17437132 | Body.0     |      23 | 17437132_Body.0_23_31 | SDS
     | {31}          | f               | 17437132_Body.0_23_7-8 | HP:0012210   | {7,8}          |
    | 17437132_Body.0_23_31_17437132_Body.0_23_7-8 | 17437132 | Body.0     |      23 | 17437132_Body.0_23_31 | SDS
     | {31}          | f               | 17437132_Body.0_23_7-8 | HP:0012211   | {7,8}          |
    | 17437132_Body.0_23_31_17437132_Body.0_23_7-8 | 17437132 | Body.0     |      23 | 17437132_Body.0_23_31 | SDS
     | {31}          | f               | 17437132_Body.0_23_7-8 | HP:0012211   | {7,8}          |
(8 rows)

**Comment by Colossus** [comment]
As it turns out, we sometimes pick up different phenos for the same word sequence. (However, even so we seem to have duplicates.) We have to discuss this

**Comment by Colossus** [comment]
we have to reintroduce gene name and pheno entity in genepheno relation_id, as I see it. For labeling, we show exactly one genepheno entity to the user. Only this relation id should be used

**Comment by shayanzare007** [comment]
How can the same word sequence map to the different phenos? Is this expected or an artifact of the system? ie, is this normal in the world of biology or should we try to infer what's the most likely pheno associated with the word sequence?

**Comment by Colossus** [comment]
it's just a fact that happens. First of all, it currently happens if we map the same thing to different nodes in the pheno DAG. E.g. a word sequence might map to "abnormality of the kidney" and "kidney hypoplasia". Second, the pheno matching is quite fuzzy, so it's perfectly conceivable that the same sequence of words can map to two different pheno candidates.

Yes, this is to be expected; I shouldn't have told you to take the pheno entity out of the mention ID in the first place. We have to put it back. However, the supervision type should still stay out of there.

**Comment by shayanzare007** [comment]
Sure, I'll put it back there. Should we just put it on pheno (since genes don't have this problem)

**Comment by shayanzare007** [comment]
let me check how the labels will be updated

**Comment by Colossus** [comment]
I think yeah, currently only on phenos ... I wouldn't know which "canonical" identifier to take for gene mention anyways. This might be something that hits us down the road ...

**Comment by Colossus** [comment]
It would be great if you could also update the labels in labeling/labels . However, I wouldn't start on this issue before I've resolved #305 first

**Comment by Colossus** [comment]
Resolving #305 will get us rid of 95% of all "duplicates". Currently you'd have the problem of deciding which pheno entity to take for the existing labels . After #305 , you won't have this problem 95% of the time (or it will even vanish)

**Comment by ajratner** [comment]
@Colossus @youssefahres So this is the problem we were referring to
whenever we talked about needing to do _entity linking_... I guess it has
hit sooner than expected!

One issue with keeping these 'duplicates', and just de-duping by adding in
e.g. pheno_entity to the relation_id, is that this could bias our learned
model towards relations including phenos with multiple matches... and
there's no a priori reason to think this is a good thing.  How many of
these duplicates are there?

I agree that trying to tackle #305 first would be better... then we can
re-evaluate this one?

**Comment by Colossus** [comment]
there are astonishingly few duplicates actually. as said, by far the most of these come from tagging the same word sequence with various synonyms of the same pheno, or with phenos that are just one node above the original pheno in the dag
