### ISSUE TITLE
Get rid of MGI in Charite

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#306]
A good part of what's currently in our charite set is actually from MGI (mouse genome information), not from MIM (mendelian inheritance in man) or ORPHANET (portal for rare diseases and orphan drugs). We should clean it up ... I think we don't want mouse information in our DS data; and we don't want to compare against it either

**Comment by Colossus** [comment]
So about 1/4 of Charite is MGI apparently

**Comment by ajratner** [comment]
Wow, okay so more motivation to create one single function to access
Charite?  This was an issue before, we have several different functions
accessing it I think...

either way nice find!!

**Comment by Colossus** [comment]
Yeah I just wanted to build our own "Charite". We're currently still using this file Harendra gave us (which they used half a year ago for their patient analysis). So first of all I want to update this regularly and then I want to make sure that what's in there is what we want ...

**Comment by Colossus** [comment]
OTOH Aaron warned me this week against taking the latest build because it exploded in size compared to the last build; so we also have to be careful there I guess

**Comment by Colossus** [comment]
To be honest, this was probably clear on Harendra's part ... I think Aaron and Harendra actually want MGI information as well. However, I think it's useless to us in terms of distant supervision, and unfair in terms of recall analysis
