### ISSUE TITLE
Adapt Mindtagger Instance for Genepheno Precision alone

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#312]
Copy labeling/templates/genepheno-holdout or adapt labeling/templates/genepheno-precision in order to label only sentences with expectation > 0.9 to better estimate precision. You should modify at least input.sql , or (to add features) also template.html

**Comment by ThomasPalomares** [comment]
Closed in 47e114c016d5fd505cff81ad7b47fac6ef8050bf
