### ISSUE TITLE
Joint factors for deciding between multiple gp mentions

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#335]

**Comment by Colossus** [comment]
I implemented a joint factor for this purpose, but it fails on two ddlog issues currently:
- NOT doesn't work; the exclamation mark isn't parsed in factors
- There is not way to do array indexing (for word index comparisons) in DDLog

**Comment by ThomasPalomares** [comment]
the "not" issue seems to be fixed with the https://github.com/HazyResearch/ddlog/pull/80 PR in ddlog. Hopefully the array indexing should be fixed soon !

**Comment by Colossus** [comment]
Work on 12647363_Abstract.0_1_50_12647363_Abstract.0_1_16-17-18
