### ISSUE TITLE
Try mixing treedlib and ddlib features

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#338]
Using treedlib only for sentences with >= 2 genes and >= 2 phenos resulted in high precision, but very low recall at 0.9 --- at 0.5, precision and recall were about the same as before. 

Still an interesting result I'd say, but how about we try mixing them.

**Comment by ajratner** [comment]
I'll also add a way to essentially do this as part of treedlib (i.e. add
sequence features to treedlib as option) too, hopefully later this week
