### ISSUE TITLE
Fix the genes canonical/noncanonical issue

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#37]
Find out if we use noncanonical gene names.
If we use noncanonical gene names, MARK AS OBSOLETE.
Otherwise, implement noncanonical gene names. Figure out what the issues are! There are a lot of gene names coming in then and there will be clashes with other abbreviations and english words.

**Comment by Colossus** [comment]
@ajratner 
The situation is this:
- In the gene mention extractor, both canonical (like "TNMD")  and noncanonical (like "tendin") and apparently even more exotic gene names like the RefSeq number and the ensembl gene number are used. This is the reason why stuff like the word "spatial" is marked as a gene.
- In the gene-phenotype-relationship extractor, however, only canonical gene names are used.
- When integrating Harendra's new gene-pheno relationship dataset from Charite and a couple other sources, I left it this way, because we're aiming for high precision.
- Because we're aiming for high precision, I'm not totally sure why we're using noncanonical gene names in the gene-mention-only extractor.
- However, when deciding we're going for recall, we should make the switch to include noncanonical gene names in the gene-pheno-relationship extractor as well.

**Comment by ajratner** [comment]
@Colossus sounds good.  Yeah I think the discrepancy here is just a hack i.e. I only made a change at the GP level because it was the smallest diff way to do this.  I guess really we should exclude non-canonical more properly via a switch in the config file, will add this now

**Comment by Colossus** [comment]
@ajratner I saw you added a switch to the config file. That's good, but it's only half of the truth. The "real" switch is what happens in the input files --- e.g., onto/data/canon_phenotype_to_gene.map . Unless you include noncanonical gene names in this file, changing the config file value will have little effect. But it's good it's there nonetheless, thanks.

**Comment by ajratner** [comment]
@Colossus I think the change I made is sufficient to have concrete effect.  The switch determines what types- canonical, noncanonical, refseq- we consider as gene mention candidates.

If the Charite supervision data `onto/data/canon_phenotype_to_gene.map` doesn't include e.g. noncanonicals, the system can still learn to consider these in GP relations, if they are candidates.  So while having noncanonical genes in our supervision data would be ideal for utilizing them, to the system, a gene candidate is a gene candidate, so we'd be fine...
