### ISSUE TITLE
GP: Add Multinomial {causation, association, NONE}

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#43]
**Switch everything -> multinomial for GP inference**

This includes changing the mindtagger template, the config VALS, the distant supervision rules, application.conf, etc.

We think that this will better structure our efforts and avoid a lot of the confusion / debate around this issue.  Basically, we have many examples that meet the **"Things Aaron would find interesting"** bar but are not "causal", and we would like to retain these in some structured manner

Also, as recap: this is not a philosophical distinction (for the most part) but a methodological one.  As example of two extremes:
- Causative link: "We knocked out X in mice and they got headaches"
- Associative link: "We performed a GWAS study on a mouse population and found a slight statistical correlation between X and headaches"

**Comment by Colossus** [comment]
@ajratner One problem with the multinomial is the following: When using a multinomial, the "causative" category would be strictly disjoint from the "associative" category. I think what we'd actually want is a schema where causative statements are a strict subset of associative statements, because a causative sentence also states and association.

[... ignore previous statement about imply function ...; I guess the way it works is "if either genepheno relationship = causative or genepheno relationship = associative then gene mention is correct"]

However, I'm not even sure if the imply function supports multinomial variables --- do you know how this would work?

Instead, I'm in favor of introducing two tables in place of the old one --- one for associative and one for causative relationships. This way, we're basically getting a multinomial with subset support, and the gene/pheno to genepheno links wouldn't be a problem either.

**Comment by Colossus** [comment]
Hmmm ... I tried the Imply with 

```
function: "Imply(Equal(genepheno_relations.relationship_tag, 2), gene_mentions.is_correct)"
```

now, but it doesn't seem to work --- `run.sh` terminates and points to this line

**Comment by Colossus** [comment]
Just trying with two tables and predictably, this leads to tons of code duplication, particularly in `application.conf`. I haven't yet gotten around to the UDFs, where refactoring to avoid duplicate code will be a little easier, but I don't know how we really want to handle this.

**Comment by Colossus** [comment]
Perhaps in this case it would really be better to separate candidate extraction and distant supervision; I think we could possibly save some duplicate code by first extracting candidates into genepheno_relations and then copying genepheno_relations into genepheno_causation and genepheno_association

**Comment by Colossus** [comment]
One advantage of the multi-table scheme is that we can use a positive-negative supervision rule implication scheme: Negative association supervision rules are automatically used in causation too; positive causation rules are automatically used in association too

**Comment by ajratner** [comment]
@Colossus I like all of your comments / ideas post-suggesting that we use two boolean variables instead of a multinomial, however I have a few concerns with this premise

**First:** either way you arrange things, the multinomial version of the code should be much cleaner (I will comment on how to implement this next, I think want to do it without `Imply` but need to confirm this...)

**Second: I am a bit wary of the statement that "causal" should be a subset of "associative", because this sounds like we are thinking of the distinction in the philosophical / theoretical sense of causation v. correlation, rather than in the (slightly) more grounded methodology-based one I thought we had been aiming to use...**  In other words, if we mean this distinction in the "knockout a mouse gene" vs. "GWAS" sense, then they should be disjoint!  And I think we are setting a more feasible bar for ourselves if we aim for this?

I still need to think this all over though, could be convinced either way still...

**Comment by ajratner** [comment]
@Colossus Actually never mind, changing my mind

I still stand by my sentiment in my second point above about how we should be thinking about / approaching the distinction

However, if there's no strong need for the label assignments to create disjoint sets, than two boolean variables as you suggested should be more flexible.

Then, again as you discuss, code reuse is key.  There should be some shared distant supervision rules that are automatically applied to both, and then some that apply to one of the two specifically (e.g. a lot of our DS rules which negatively label phrases involving "association"-type patterns)

I'll take a look at what you've started coding up in a bit but sounds good, I'm on board!

I think as long in as making this switch to two vars we can keep the code nearly as simple / clean as before with one, then shouldn't be much downside!

**Comment by ajratner** [comment]
@Colossus the code on the `multinomial` branch looks in-progress (e.g. `application.conf`) so I'll wait to look over but lmk.  I agree with separating candidate extraction & supervision as it looks like you started doing

FYI comments are good for general questions, if one of us wants the other to review a major addition (e.g. merging `multinomial` into `master`) then pull requests are good for this.  I like using them when working w other ppl- I often push small changes to master but anything with a whole separate branch can  do pull request, then the other person can review, merge & delete the branch

Main / best value of this I think is that it forces multiple people to remain aware of how the codebase is evolving!

**Comment by Colossus** [comment]
@ajratner Sounds good, I'll continue sorting it out and I'll notify you as soon as I think I have something working.

**Comment by Colossus** [comment]
@ajratner Hey Alex, I'm just trying to run the pheno_extract_candidates again, but it still fails with a memory error. The table is empty currently, unfortunately, so I can't test my new stuff (and I'm pretty sure there's lots of little to medium-sized errors to fix in there).

Does the pheno-mention-extractor work again on your side?

**Comment by ajratner** [comment]
@Colossus Sorry, see my comments on #42 and #44.

To run for now you can just reduce the PARALLELISM for the pheno candidate extractor in `application.conf`, so that it fits in memory, then it does run successfully... 

I will address these issues soon although can't right now

**Comment by Colossus** [comment]
@ajratner OK cool thanks
