### ISSUE TITLE
Make pheno_extract_candidates less top-heavy!

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#44]
Reduce size of loaded data structures

**Comment by Colossus** [comment]
CF here: http://stackoverflow.com/questions/25108014/python-defaultdict-for-large-data-sets

**Comment by ajratner** [comment]
@Colossus I think this isn't too high on our priority list right now due to your #42 fix correct, right?

Can always re-open this

**Comment by Colossus** [comment]
@ajratner Yeah sure, sounds good
