### ISSUE TITLE
Remove sentences from current sentences_input that do not contain a gene name

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#45]
Basically for speed. This should cut our sentences_input size by a factor of 8.

**Comment by ajratner** [comment]
@Colossus as long as we keep the original data somewhere e.g. another table
am fine w this

**Comment by Colossus** [comment]
@ajratner Run `./run.sh only_sentences_with_genes` after `./run.sh new_sentences` to do the join on gene mentions. I finally joined on all of gene_mentions, the reason being that we also negatively supervise gene mentions where a parenthesis occurs before the gene name and so on, which I wanted to keep.
