### ISSUE TITLE
Load PMID to HPO via mesh into database table + add PMID column to sentences_input

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#46]

**Comment by Colossus** [comment]
@ajratner Is there any documentation on how to "recreate" the current 50/50 split sentences_input table? I'm just trying to run `./run.sh /dfs/scratch0/ajratner/dd_raw_docs/PLoS_ONE/PLoS_ONE_2006_Dec_20_1\(1\)_e100.nxml sentences_input new` on one of my databases, but I get: 

```
Using bazaar installation at /lfs/local/0/jbirgmei/bazaar
Parsing XML docs
Running NLP preprocessing
NO MATCH
parallelism = 80
batch-size  = 1000
/lfs/local/0/jbirgmei/bazaar/parser/run.sh -i json -k item_id -v content
/lfs/local/0/jbirgmei/bazaar/parser/run.sh: line 5: /lfs/local/0/jbirgmei/bazaar/parser/target/start: No such file or directory
Adding to existing table sentences_input in db
Copying to sentences_input table in database genomics_jbirgmei_50k
cat: xml_parsed.json.split/*.parsed: No such file or directory
To clean up, run: rm -rf xml_parsed.json*
```

**Comment by Colossus** [comment]
@ajratner where the important part is that it doesn't find one of these scripts, and nothing happens. And I think even if it worked, I wouldn't know how to recreate the current `sentences_input` table.

**Comment by ajratner** [comment]
@Colossus which `run.sh` script is this (abs path)?

**Comment by ajratner** [comment]
@Colossus I think you need to build the `bazaar/parser` code, see [the README.md](https://github.com/HazyResearch/bazaar/tree/master/parser) in `bazaar/parser`

**Comment by ajratner** [comment]
@Colossus Then to recreate the 50/50 split table I just used some SQL, not sure if I wrote it down anywhere but I just took all the `WHERE doc_id NOT LIKE '%one%'` and then the same number of the complement set...

**Comment by Colossus** [comment]
@ajratner it was the `run.sh` in `/lfs/raiders2/0/jbirgmei/dd-genomics/parser`, but you're right, I need to run `setup.sh` in the `bazaar/parser` directory

**Comment by Colossus** [comment]
Changing this objective on this, have a much better and easier solution

**Comment by Colossus** [comment]
@ajratner It turns out, for obvious reasons, that of the 16,917,165 lines in `onto/data/hpo_to_pmid_via_mesh.tsv`, we're using only those for which we can also map the PMID to a DOI (our documents key). By simply pre-joining `hpo_to_pmid_via_mesh.tsv` with the DOI mapping, the size of the file is reduced to 0.3%, or about 60,000 lines, which easily fit into memory. The runtime of the pheno candidate extractor is roughly halved, the results are exactly the same. Please execute:

```
cd onto/data
sort -k2,2 hpo_to_pmid_via_mesh.tsv > hpo_to_pmid_via_mesh_sortk2.tsv
sort -k2,2 plos_doi_to_pmid.tsv > plos_doi_to_pmid_sortk2.tsv
join -1 2 -2 2 hpo_to_pmid_via_mesh_sortk2.tsv plos_doi_to_pmid_sortk2.tsv | awk '{print $2"\t"$1}' > hpo_to_pmid_via_mesh_with_doi.tsv
```

**Comment by gbgbg** [comment]
To make my (uncalled for :) debut on the forum - JB, you can bias the non Plos one towards more caluable ploses. Plos genetics, maybe biology maybe comp bio - you can look at the OMIM distribution. 
-Gill

**Comment by Colossus** [comment]
@gbgbg OK, we can definitely do that. But we're not using the current dataset for anything serious anyways. When we're extracting for Aaron, we're gonna use all available data anyways.
