### ISSUE TITLE
Association VS. Causation supervision rules

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#48]
Now we have the association vs. causation multinomial, let's get real and make supervision rules to sharply distinguish between the two sentence types.

**Comment by ajratner** [comment]
@Colossus How much work do you think needs to be done here?

I guess we need the holdout set to get a better view of where we are here...

**Comment by Colossus** [comment]
Yeah I think so

**Comment by ajratner** [comment]
Closing until we have specific issues with current code...
