### ISSUE TITLE
Switch to faster extractors?

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#56]
We are currently using the `tsv_extractor`.  Should we switch to e.g. `plpy` or `piggy` extractor?

@netj any comments on what best practices are for this right now?

Also, more minor: right now we pre-convert postgres arrays to strings (`sentences` -> `sentences_input`) is this actually saving any time?  Would be cleaner / simpler to do without this.  May change if we switch extractors.

**Comment by netj** [comment]
I'd advise to stay with `tsv_extractor`.  We're planning to put more engineering effort into making the simplest extractor style more efficient.  You may get some initial speedup with `plpy` or `piggy`, but I'm afraid locking your code into a specific style may not pay off in the longer run.

Regarding the issue of array vs. string column in sentences table, according to @SenWu it sounds like that was a quick hack to avoid the need to parse PostgreSQL's array serialization.  I think you can get rid of that extra data duplication step, once you get a nice Python code that can parse Postgres arrays.  I have a [JavaScript version in Mindtagger](https://github.com/HazyResearch/mindbender/blob/master/gui/frontend/src/mindtagger/array-parsers.coffee) with [some tests that check corner cases](https://github.com/HazyResearch/mindbender/blob/master/gui/frontend/src/mindtagger/array-parsers_test.coffee) which may help.

**Comment by ajratner** [comment]
@netj thanks!

Yeah I think I do actually have code in our `extractor_util.py` file to parse postgres arrays, but just never switched / was assuming there was some scary encoding parsing reason to do it in psql... I'll check out @SenWu's stuff, thanks!
