### ISSUE TITLE
Refactor onto/make_all.sh- is 248 lines & scary!!

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#64]
Not a priority exactly but should do at some point; delete unused lines & comment a few things better...

**Comment by Colossus** [comment]
I agree, but do we want to change it? Don't fix it if it isn't broken ... what the whole thing does is download a bunch of stuff and then do some more of less crude combinations of awk, cut, grep, join and friends. It's not really dangerous

**Comment by ajratner** [comment]
@Colossus I agree, my only concern is for down the road- e.g. if one of the resources changes, or we encounter a bug like in #24, then the current format will significantly slow down what should be simple fixes.

But again I didn't mean for this to be high priority though- only a marker for if we refactor at some point.  Am fine if we close it for now

**Comment by ajratner** [comment]
Quick note- I think all that we should do for now is go through `onto/` and delete stuff we're not using at all (including related lines in `make_all.sh`), make sure what we are using is commented, but leave everything else as is- then can close this.

Doing this in person together might be helpful; but again not high priority
