### ISSUE TITLE
Inference fails at grounding stage (see attached error msg)

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#65]
`22:19:11 [taskManager] INFO  Completed task_id=inference_grounding with Failure(org.postgresql.util.PSQLException: ERROR: Error when close writable externtal table (url.c:1791)`

@Colossus has this happened to you at all lately?

@netj I see a lot of your processes running on raiders2- could lack of memory be the problem here?

**Comment by Colossus** [comment]
No, hasn't happens at all to me

**Comment by netj** [comment]
@ajratner I don't think I had any actively running processes there.  I'll try not to leave them around though.  The error message suggests unloading data from the database isn't working.  This is probably due to gpfdist not running.  This seems related to #63.
