### ISSUE TITLE
Debug titles only extraction

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#68]
After looking at a few titles, it seems our extractors do considerably worse on titles only because of their peculiar wording. Abstracts do comparably to body text, it seems. We should investigate more thoroughly.

**Comment by ajratner** [comment]
Interesting- I guess this confirms what Chris said about expecting the
different sections to need different models! What are some examples of the
divergences?

**Comment by Colossus** [comment]
It seems to have trouble picking the right gene and phenotype in sentences such as this one:

**"CD2 promoter regulated nucleophosmin-anaplastic lymphoma kinase in transgenic mice causes B lymphoid malignancy."**: it picks _CD2_ and _lymphoma_, but _lymphoma_ is part of _nucleophosmin-anaplastic lymphoma kinase_. In particular, it seems (and from my moderate understanding of the literature, this is quite common) that in titles, gene and protein names that are usually abbreviated in text are often spelled out.

**Mutational analysis reveals the FUS homolog TAF15 as a candidate gene for familial amyotrophic lateral sclerosis**: It picks _FUS_ and _amyotrophic lateral sclerosis_. This is obviously confusing for the extractor, but people try to establish as much context in the title as possible (see also above example with the "blah-regulated gene"), and the right gene to pick here is _TAF15_. Another example, where DeepDive picked the correct things (also b/c presumably they were the only things to pick):  **Autophagy-Related _ IRGM _ Polymorphism Is Associated with Mortality of Patients with Severe Sepsis**. (Autophagy is a bodily process involved in destruction/degradation of cells, so not a phenotype.)

Next wrong example: **Polymorphism at the TNF superfamily gene TNFSF4 confers susceptibility to systemic lupus erythematosus**: it picked _TNF_ and _systemic lupus erythematosus_. The correct gene would have been _TNFSF4_. Again, establishing context within the title by referencing the more widely known gene flusters our extractor.

**Comment by Colossus** [comment]
Hmmm. After going through a titles-only extractor, the situation seems way less dire. We have high precision again. Did I by pure chance just select a particularly bad subset of titles and abstracts, cited above? The titles-only extractor just produced ~90% precision again, but the causation vs. association scores are sometimes off.

**Comment by gbgbg** [comment]
I'd be curious what the dependency path looks like in the examples below. 

CD2 promoter regulated blah ...
... reveals the FAS homolog blah ...
... at the TNF superfamily gene blah ...

You would hope in all three cases blah is the subject ?!

-Gill

**Comment by gbgbg** [comment]
I am curious if you try to pick on sentences that contain a G-P relationship, with sentences of similar structure/s to the ones you found are wrong below, do they consistently make the same mistake?
- G not subject 
- gene1 homolog gene2 
- gene2 superfamily gene2 

Maybe it's over optimization...

-Gill

**Comment by Colossus** [comment]
not in current philosophy
