### ISSUE TITLE
REDO SCHEMA: separate doc_id, section_id, sent_id, ref_doc_id

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#84]
This should be a mostly superficial change but I think it is worth doing now to avoid future confusions / hack-ey workarounds.  Basically `doc_id` will be renamed `section_id` and remain the primary key that e.g. the tables are partitioned on in greenplum, queries are joined on etc.  `sent_id` counts will restart for every `section_id`.  `doc_id` will be the overall article id for reference / convenience.  E.g.:
- `doc_id: 12345`
- `section_id: 12345.Abstract.0`
- `sent_id: 12`

**Comment by ajratner** [comment]
Done in the parser code; need to just change this everywhere else in the dd-genomics codebase...

**Comment by ajratner** [comment]
**New schema:**
- `doc_id: 12345`
- `section_id: Ref.0`
- `sent_id: 0`
- `ref_doc_id: 23456`

**Comment by Colossus** [comment]
@Colossus note to self. Stuff that needs to be adapted:
- API
- Main code
- Dashboard
- Mindtagger
- View

**Comment by Colossus** [comment]
Mindtagger should be done

**Comment by Colossus** [comment]
API should be done --- hope it works, was only one line
