### ISSUE TITLE
PNAS not in PMC?  Missing any others?

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#91]

**Comment by gbgbg** [comment]
Semi aside: Johannes was alarmed by PNAS's absence particularly because 
PNAS is the second most common journal we see in OMIM. I doubt the OMIM 
survey was super exact. In particular we may want to consider counting 
references only for the OMIM section/s we care about most (eg allelic 
variants of genes).

If CPU time becomes expensive and we want to clean by journal names - 
i'd look back at the survey before making further decisions based on it.

**Comment by amwenger** [comment]
PubmedCentral claims that [PNAS is a "full participation" journal](http://www.ncbi.nlm.nih.gov/pmc/journals/?term=Proceedings%20of%20the%20National%20Academy%20of%20Sciences%20of%20the%20United%20States%20of%20America&titles=all&search=journals):
![screen shot 2015-08-02 at 9 48 35 am](https://cloud.githubusercontent.com/assets/7155109/9027075/b59f335c-38fb-11e5-8284-c691692624ab.png)

![screen shot 2015-08-02 at 9 51 18 am](https://cloud.githubusercontent.com/assets/7155109/9027081/0b60b284-38fc-11e5-87bd-65ffae59fa42.png)

I'm not sure it matters much anyway.  I would just take what PMC has to start.  That will get us most of the way there.  We can plug holes later.  But perhaps others advocate a different approach.

**Comment by amwenger** [comment]
PNAS articles are on the [PMC article list](http://www.ncbi.nlm.nih.gov/pmc/tools/ftp/):

> curl ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/PMC-ids.csv.gz | zcat |
>    awk -F',' '($NF ~ /live/) { print $1 "\t" $4; }' | grep 'Proc Natl Acad Sci U S A' |
>    sort | tac | uniq -c | head

```
 773 Proc Natl Acad Sci U S A        2015
4247 Proc Natl Acad Sci U S A        2014
4636 Proc Natl Acad Sci U S A        2013
4464 Proc Natl Acad Sci U S A        2012
4161 Proc Natl Acad Sci U S A        2011
4256 Proc Natl Acad Sci U S A        2010
4438 Proc Natl Acad Sci U S A        2009
4007 Proc Natl Acad Sci U S A        2008
3774 Proc Natl Acad Sci U S A        2007
3699 Proc Natl Acad Sci U S A        2006
```

**Comment by gbgbg** [comment]
I'm fine w plugging holes later. Dashboard's first role is to help us spot holes. I hope it served Johannes to discover this seeming omission. Then things go in the queue and can be prioritized as we see fit...

**Comment by ajratner** [comment]
Issues board! :)

**Comment by amwenger** [comment]
I think I get it now.  PNAS is part of PMC, but not the "open access" subset of PMC that is available for bulk download.

@Colossus Is that right?

**Comment by gbgbg** [comment]
I suspect that @amwenger is right. 
I suspect what we have is PMCOA
Which is a strict subset of PMC 
Hard to triangulate fully on the phone. 
I trust @collosus will look into it 

http://www.ncbi.nlm.nih.gov/pmc/about/faq/
http://www.ncbi.nlm.nih.gov/pmc/tools/openftlist/

-Gill

**Comment by Colossus** [comment]
@amwenger @gbgbg I honestly don't know. I only know what I googled (and it seems you already know more than me). I didn't even know a subset of PMC called PMCOA existed ... I was under the impression we downloaded all of PMC, which turned out to be wrong because PNAS is missing.

**Comment by ajratner** [comment]
If you look at the DeepDive open dataset page, we have PMC-OA, so this is
correct

**Comment by gbgbg** [comment]
We didn't think you knew. We are hoping you'd conclusively get to the bottom of it. 

As we said before: it's like the matrix. Everywhere you look closely enough for the first time the pill will wear off. The more of the present we see for what it really is, the better we prioritize the future to have a pill free killer app.

**Comment by ajratner** [comment]
I'm going to close this, if I'm misinterpreting feel free to re-open...
