### ISSUE TITLE
Run PubMed through parser

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#98]

**Comment by Colossus** [comment]
Congrats!

**Comment by ajratner** [comment]
Haha thanks :)

**Comment by gbgbg** [comment]
Can we do congrats _plus_ quality assurance ? :)

-Gill

**Comment by ajratner** [comment]
Of course :)! Almost there... A few DeepDive bugs running on this large of
a set but getting there (pheno ran, Gene hopefully fixed and runs
tonight...)
